export interface EncyclopediaEntry {
  id: string;
  name: string;
  distillery: string;
  region: string;
  country: string;
  category: string;
  age: number | null;
  abv: number;
  nose: string;
  palate: string;
  finish: string;
  description: string;
  priceRange: string;
  difficulty: "입문" | "중급" | "상급";
  tags: string[];
}

export const ENCYCLOPEDIA_WHISKEYS: EncyclopediaEntry[] = [
  {
    id: "glenlivet-12", name: "The Glenlivet 12", distillery: "The Glenlivet",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "꽃향, 바닐라, 열대과일", palate: "부드러운 오크, 파인애플, 복숭아", finish: "가볍고 달콤한 여운",
    description: "스피사이드를 대표하는 입문용 싱글몰트. 깔끔하고 달콤한 풍미로 위스키 입문자에게 추천.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "달콤함", "입문추천"],
  },
  {
    id: "glenfiddich-12", name: "Glenfiddich 12", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "신선한 배, 크리미한 토피", palate: "배, 오크, 은은한 스파이스", finish: "부드럽고 짧은 여운",
    description: "세계에서 가장 많이 팔리는 싱글몰트. 접근성이 좋고 균형 잡힌 맛.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "과일향", "입문추천"],
  },
  {
    id: "macallan-12", name: "The Macallan 12 Sherry Oak", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "건포도, 무화과, 진저", palate: "풍부한 셰리, 초콜릿, 오렌지 껍질", finish: "길고 따뜻한 스파이시 여운",
    description: "셰리 오크 캐스크의 정수. 달콤하고 과일향 풍부한 스피사이드 대표작.",
    priceRange: "₩90,000–120,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "셰리캐스크", "초콜릿"],
  },
  {
    id: "lagavulin-16", name: "Lagavulin 16", distillery: "Lagavulin",
    region: "Islay", country: "Scotland", category: "스카치", age: 16, abv: 43,
    nose: "강렬한 피트, 바다소금, 스모키", palate: "두꺼운 피트, 스위트몰트, 아이오딘", finish: "매우 길고 드라이한 스모키 여운",
    description: "아일라 피트 위스키의 교과서. 강렬하고 복잡한 스모키 풍미의 정점.",
    priceRange: "₩100,000–140,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "스모키", "강렬함"],
  },
  {
    id: "laphroaig-10", name: "Laphroaig 10", distillery: "Laphroaig",
    region: "Islay", country: "Scotland", category: "스카치", age: 10, abv: 40,
    nose: "병원 소독약, 해초, 피트", palate: "스모키, 달콤함, 소금기", finish: "길고 드라이, 약품향 여운",
    description: "좋아하거나 싫어하거나. 아이오딘과 피트의 극단적 조합으로 독보적 개성.",
    priceRange: "₩55,000–75,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "아이오딘", "개성강함"],
  },
  {
    id: "highland-park-12", name: "Highland Park 12", distillery: "Highland Park",
    region: "Highland (Orkney)", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "꿀, 헤더, 은은한 피트", palate: "과일, 스파이스, 부드러운 스모키", finish: "균형 잡힌 달콤함과 피트 여운",
    description: "피트와 달콤함의 완벽한 균형. 오크니 섬의 바이킹 정신을 담은 위스키.",
    priceRange: "₩55,000–70,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "밸런스", "꿀향"],
  },
  {
    id: "oban-14", name: "Oban 14", distillery: "Oban",
    region: "West Highland", country: "Scotland", category: "스카치", age: 14, abv: 43,
    nose: "바다소금, 꿀, 은은한 피트", palate: "드라이한 오크, 견과류, 과일향", finish: "따뜻하고 긴 스파이시 여운",
    description: "하이랜드와 아일라의 중간 지점. 해양성과 달콤함이 조화로운 명작.",
    priceRange: "₩80,000–105,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "해양성", "균형"],
  },
  {
    id: "glenmorangie-10", name: "Glenmorangie The Original 10", distillery: "Glenmorangie",
    region: "Highland", country: "Scotland", category: "스카치", age: 10, abv: 40,
    nose: "복숭아, 오렌지, 레몬그라스", palate: "바닐라, 크림, 복숭아", finish: "길고 부드러운 달콤한 여운",
    description: "높은 증류기에서 나오는 섬세한 풍미. 화사한 꽃향과 과일향의 하이랜드 입문작.",
    priceRange: "₩55,000–70,000", difficulty: "입문", tags: ["싱글몰트", "Highland", "꽃향", "과일향"],
  },
  {
    id: "jameson", name: "Jameson Original", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "가벼운 스파이스, 맥아, 나무향", palate: "부드러운 그레인, 바닐라, 견과류", finish: "깔끔하고 짧은 여운",
    description: "세계에서 가장 많이 팔리는 아이리쉬 위스키. 트리플 디스틸드의 부드러움.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "부드러움", "입문추천"],
  },
  {
    id: "redbreast-12", name: "Redbreast 12", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: 12, abv: 40,
    nose: "셰리, 건포도, 향신료", palate: "풍부한 과일, 스파이스, 초콜릿", finish: "길고 따뜻한 스파이시 여운",
    description: "아이리쉬 팟 스틸의 정수. 풍부하고 복잡한 풍미로 아이리쉬 프리미엄 대표작.",
    priceRange: "₩65,000–85,000", difficulty: "중급", tags: ["팟스틸", "아이리쉬", "셰리캐스크", "프리미엄"],
  },
  {
    id: "green-spot", name: "Green Spot", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "신선한 사과, 보리, 스파이스", palate: "크리미, 사과, 허브", finish: "부드럽고 스파이시한 여운",
    description: "전통 팟 스틸 스타일의 희귀 아이리쉬. 과거 와인 상인들이 비축했던 스타일 재현.",
    priceRange: "₩60,000–80,000", difficulty: "중급", tags: ["팟스틸", "아이리쉬", "희귀", "전통"],
  },
  {
    id: "bushmills-original", name: "Bushmills Original", distillery: "Old Bushmills",
    region: "County Antrim", country: "Northern Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "꿀, 사과, 가벼운 바닐라", palate: "달콤한 과일, 몰트, 가벼운 스파이스", finish: "부드럽고 짧은 여운",
    description: "세계에서 가장 오래된 면허 증류소. 가볍고 달콤한 블렌디드 입문작.",
    priceRange: "₩30,000–45,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "달콤함", "역사"],
  },
  {
    id: "buffalo-trace", name: "Buffalo Trace", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "바닐라, 민트, 갈색설탕", palate: "카라멜, 바닐라, 오크", finish: "오래 지속되는 달콤한 여운",
    description: "가격 대비 품질이 뛰어난 켄터키 버번의 기준점. 부드럽고 균형 잡힌 클래식.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["버번", "Kentucky", "바닐라", "입문추천"],
  },
  {
    id: "makers-mark", name: "Maker's Mark", distillery: "Maker's Mark",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "달콤한 맥아, 바닐라, 꿀", palate: "카라멜, 버터, 부드러운 스파이스", finish: "달콤하고 따뜻한 여운",
    description: "밀 매시빌로 만든 부드러운 버번. 빨간 왁스 인장으로 유명한 아이콘.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["버번", "Kentucky", "부드러움", "밀매시빌"],
  },
  {
    id: "woodford-reserve", name: "Woodford Reserve", distillery: "Woodford Reserve",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.2,
    nose: "초콜릿, 건과일, 오렌지", palate: "풍부한 과일, 스파이스, 오크", finish: "길고 따뜻한 스파이시 여운",
    description: "트리플 디스틸드 켄터키 버번. 복잡하고 세련된 풍미로 프리미엄 버번 대표작.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["버번", "Kentucky", "트리플디스틸드", "프리미엄"],
  },
  {
    id: "wild-turkey-101", name: "Wild Turkey 101", distillery: "Wild Turkey",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50.5,
    nose: "카라멜, 바닐라, 오크", palate: "진한 캐러멜, 스파이스, 오렌지", finish: "강렬하고 긴 스파이시 여운",
    description: "101 프루프의 강렬한 버번. 오크통 풍미가 진하고 개성 넘치는 하이프루프 스탠다드.",
    priceRange: "₩40,000–55,000", difficulty: "중급", tags: ["버번", "Kentucky", "하이프루프", "강렬함"],
  },
  {
    id: "rittenhouse-rye", name: "Rittenhouse Rye", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "호밀빵, 민트, 스파이스", palate: "진한 스파이스, 후추, 달콤함", finish: "드라이하고 긴 스파이시 여운",
    description: "가성비 최고의 라이 위스키. 칵테일 베이스로도, 스트레이트로도 탁월.",
    priceRange: "₩35,000–50,000", difficulty: "중급", tags: ["라이", "Pennsylvania", "스파이시", "칵테일"],
  },
  {
    id: "bulleit-bourbon", name: "Bulleit Bourbon", distillery: "Bulleit Distilling Co. (Diageo)",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "오크, 메이플시럽, 향신료", palate: "매운 호밀향, 바닐라, 오렌지껍질", finish: "드라이하고 길게 지속되는 스파이시",
    description: "높은 라이 함량으로 스파이시한 개성. 심플한 병 디자인과 탄탄한 맛.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["버번", "Kentucky", "하이라이", "스파이시"],
  },
  {
    id: "yamazaki-12", name: "Yamazaki 12", distillery: "Yamazaki",
    region: "Osaka", country: "Japan", category: "기타", age: 12, abv: 43,
    nose: "복숭아, 파인애플, 생강", palate: "달콤한 오크, 코코넛, 미즈나라", finish: "길고 드라이하며 스파이시",
    description: "일본 위스키의 상징. 미즈나라 오크의 독특한 향과 동양적 감성의 정점.",
    priceRange: "₩150,000–250,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "미즈나라", "프리미엄"],
  },
  {
    id: "nikka-from-barrel", name: "Nikka From The Barrel", distillery: "Nikka",
    region: "Hokkaido / Miyagi", country: "Japan", category: "기타", age: null, abv: 51.4,
    nose: "캐러멜, 건포도, 바닐라", palate: "풍부한 오크, 과일, 스파이스", finish: "길고 복잡한 따뜻한 여운",
    description: "가성비 최고의 일본 블렌디드. 고도수에서 오는 묵직함과 복잡함이 특징.",
    priceRange: "₩60,000–85,000", difficulty: "중급", tags: ["블렌디드", "Japanese", "하이프루프", "가성비"],
  },
  {
    id: "kavalan-classic", name: "Kavalan Classic", distillery: "Kavalan",
    region: "Yilan", country: "Taiwan", category: "기타", age: null, abv: 40,
    nose: "트로피컬 과일, 바닐라, 복숭아", palate: "달콤한 오크, 망고, 코코넛", finish: "부드럽고 달콤한 여운",
    description: "대만의 아열대 기후가 만들어내는 빠른 숙성의 트로피컬 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "입문", tags: ["싱글몰트", "Taiwanese", "트로피컬", "달콤함"],
  },
  {
    id: "hibiki-harmony", name: "Hibiki Japanese Harmony", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: null, abv: 43,
    nose: "로즈우드, 감귤, 꿀", palate: "오렌지껍질, 달콤한 오크, 화이트초콜릿", finish: "길고 향기로운 여운",
    description: "산토리의 블렌딩 철학 집대성. 24개 면의 병처럼 24절기를 담은 하모니.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["블렌디드", "Japanese", "꽃향", "프리미엄"],
  },
  {
    id: "talisker-10", name: "Talisker 10", distillery: "Talisker",
    region: "Isle of Skye", country: "Scotland", category: "스카치", age: 10, abv: 45.8,
    nose: "후추, 해풍, 스모키", palate: "몰트 단맛, 바다소금, 페퍼", finish: "따뜻하고 후추가 남는 긴 여운",
    description: "스카이 섬 특유의 해양성과 페퍼 스파이스가 선명한 싱글몰트.",
    priceRange: "₩75,000–95,000", difficulty: "중급", tags: ["싱글몰트", "Island", "해양성", "페퍼"],
  },
  {
    id: "glendronach-12", name: "The GlenDronach 12", distillery: "The GlenDronach",
    region: "Highland", country: "Scotland", category: "스카치", age: 12, abv: 43,
    nose: "셰리, 건과일, 오렌지", palate: "건포도, 토피, 다크초콜릿", finish: "달콤하고 묵직한 셰리 여운",
    description: "올로로소/페드로 히메네즈 셰리 캐스크 숙성의 클래식한 하이랜드 스타일.",
    priceRange: "₩85,000–110,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "셰리캐스크", "건과일"],
  },
  {
    id: "balvenie-doublewood-12", name: "The Balvenie DoubleWood 12", distillery: "The Balvenie",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "꿀, 견과류, 말린과일", palate: "바닐라, 오크, 은은한 시나몬", finish: "부드럽고 달콤한 오크 여운",
    description: "버번 캐스크 후 셰리 캐스크 피니시로 균형감이 뛰어난 스페이사이드 대표작.",
    priceRange: "₩95,000–120,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "더블우드", "밸런스"],
  },
  {
    id: "monkey-shoulder", name: "Monkey Shoulder", distillery: "William Grant & Sons",
    region: "Speyside", country: "Scotland", category: "스카치", age: null, abv: 40,
    nose: "바닐라, 오렌지, 몰트", palate: "크리미한 토피, 꿀, 스파이스", finish: "가볍고 산뜻한 달콤함",
    description: "칵테일과 스트레이트 모두 부담 없이 즐기기 좋은 블렌디드 몰트.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드몰트", "Speyside", "칵테일", "입문추천"],
  },
  {
    id: "ardbeg-10", name: "Ardbeg 10", distillery: "Ardbeg",
    region: "Islay", country: "Scotland", category: "스카치", age: 10, abv: 46,
    nose: "강한 피트, 레몬, 해초", palate: "스모키, 바닐라, 블랙페퍼", finish: "길고 드라이한 피트 여운",
    description: "아일라 피트의 개성을 또렷하게 보여주는 강렬한 싱글몰트.",
    priceRange: "₩80,000–105,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "피트", "스모키"],
  },
  {
    id: "teeling-small-batch", name: "Teeling Small Batch", distillery: "Teeling",
    region: "Dublin", country: "Ireland", category: "아이리쉬", age: null, abv: 46,
    nose: "런던드라이 과일, 바닐라, 향신료", palate: "럼 캐스크의 달콤함, 오크, 후추", finish: "달콤하고 스파이시한 여운",
    description: "럼 캐스크 피니시가 개성을 더하는 현대적인 더블린 스타일 아이리쉬.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["블렌디드", "아이리쉬", "럼캐스크", "스파이시"],
  },
  {
    id: "writers-tears-copper-pot", name: "Writers' Tears Copper Pot", distillery: "Walsh Whiskey",
    region: "County Carlow", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "배, 사과, 꿀", palate: "부드러운 몰트, 바닐라, 은은한 오크", finish: "깔끔하고 고소한 여운",
    description: "싱글몰트와 싱글팟스틸 조합으로 부드럽고 우아한 과일향이 돋보인다.",
    priceRange: "₩50,000–70,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "과일향", "부드러움"],
  },
  {
    id: "tullamore-dew", name: "Tullamore D.E.W.", distillery: "Tullamore",
    region: "County Offaly", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "레몬 제스트, 바닐라, 시리얼", palate: "가벼운 몰트, 꿀, 스파이스", finish: "짧고 깔끔한 곡물 여운",
    description: "가볍고 산뜻한 스타일로 하이볼이나 데일리 드링크에 잘 맞는 아이리쉬.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "하이볼", "데일리"],
  },
  {
    id: "powers-gold-label", name: "Powers Gold Label", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 43.2,
    nose: "시나몬, 꿀, 곡물", palate: "오일리한 질감, 스파이스, 토피", finish: "따뜻하고 드라이한 향신료 여운",
    description: "전통적인 아이리쉬 스파이스가 살아있는 클래식 블렌드.",
    priceRange: "₩45,000–65,000", difficulty: "중급", tags: ["블렌디드", "아이리쉬", "스파이시", "클래식"],
  },
  {
    id: "bushmills-10", name: "Bushmills 10 Year Old", distillery: "Old Bushmills",
    region: "County Antrim", country: "Northern Ireland", category: "아이리쉬", age: 10, abv: 40,
    nose: "꿀, 바닐라, 잘 익은 과일", palate: "밀크초콜릿, 몰트, 사과", finish: "부드럽고 은은한 단맛",
    description: "셰리/버번 캐스크의 균형으로 입문자에게 편안한 10년 숙성 싱글몰트.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["싱글몰트", "아이리쉬", "10년", "입문추천"],
  },
  {
    id: "four-roses-single-barrel", name: "Four Roses Single Barrel", distillery: "Four Roses",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "체리, 바닐라, 오크", palate: "카라멜, 후추, 잘 익은 과일", finish: "길고 스파이시한 버번 여운",
    description: "싱글 배럴 특유의 농도와 향신료감이 살아있는 프리미엄 버번.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["버번", "Kentucky", "싱글배럴", "스파이시"],
  },
  {
    id: "knob-creek-9", name: "Knob Creek 9", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 9, abv: 50,
    nose: "바닐라, 구운오크, 땅콩", palate: "묵직한 캐러멜, 시나몬, 오크", finish: "길고 따뜻한 오크 스파이스",
    description: "9년 숙성과 100프루프 바디감으로 클래식한 풀바디 버번을 보여준다.",
    priceRange: "₩60,000–85,000", difficulty: "중급", tags: ["버번", "Kentucky", "100프루프", "풀바디"],
  },
  {
    id: "elijah-craig-small-batch", name: "Elijah Craig Small Batch", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 47,
    nose: "토피, 오렌지, 오크", palate: "바닐라, 넛맥, 캐러멜", finish: "중간 길이의 달콤한 스파이스",
    description: "버번의 밸런스를 잘 보여주는 스몰 배치 스타일의 스테디셀러.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["버번", "Kentucky", "스몰배치", "밸런스"],
  },
  {
    id: "evan-williams-single-barrel", name: "Evan Williams Single Barrel", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.3,
    nose: "사과, 토피, 바닐라", palate: "오크, 시나몬, 라이트 초콜릿", finish: "부드럽고 은은한 단맛",
    description: "부담 없는 가격대에서 싱글 배럴 개성을 체험하기 좋은 버번.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["버번", "Kentucky", "싱글배럴", "가성비"],
  },
  {
    id: "bulleit-rye", name: "Bulleit Rye", distillery: "MGP",
    region: "Indiana", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "민트, 딜, 시트러스", palate: "라이 스파이스, 꿀, 오크", finish: "드라이하고 선명한 허브 여운",
    description: "칵테일 베이스로 특히 인기가 높은 스파이시한 라이 위스키.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["라이", "Indiana", "칵테일", "스파이시"],
  },
  {
    id: "hakushu-12", name: "Hakushu 12", distillery: "Hakushu",
    region: "Yamanashi", country: "Japan", category: "기타", age: 12, abv: 43,
    nose: "허브, 청사과, 은은한 스모크", palate: "민트, 배, 가벼운 오크", finish: "맑고 시원한 허벌 여운",
    description: "산림 증류소의 청량한 스타일을 보여주는 일본 싱글몰트 대표작.",
    priceRange: "₩200,000–320,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "허브", "프리미엄"],
  },
  {
    id: "suntory-toki", name: "Suntory Toki", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: null, abv: 43,
    nose: "바질, 청사과, 꿀", palate: "가벼운 바닐라, 시트러스, 곡물", finish: "짧고 깨끗한 여운",
    description: "하이볼 친화적인 라이트 블렌드로 일본 위스키 입문에 적합하다.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "하이볼", "입문추천"],
  },
  {
    id: "nikka-days", name: "Nikka Days", distillery: "Nikka",
    region: "Hokkaido / Miyagi", country: "Japan", category: "기타", age: null, abv: 40,
    nose: "시리얼, 바닐라, 가벼운 과일", palate: "부드러운 몰트, 배, 토피", finish: "은은하고 매끈한 여운",
    description: "데일리 음용을 겨냥한 가벼운 스타일의 일본 블렌디드 위스키.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "데일리", "부드러움"],
  },
  {
    id: "paul-john-brilliance", name: "Paul John Brilliance", distillery: "Paul John",
    region: "Goa", country: "India", category: "기타", age: null, abv: 46,
    nose: "꿀, 오렌지 필, 바닐라", palate: "보리 단맛, 시나몬, 견과류", finish: "따뜻하고 스파이시한 여운",
    description: "인도 싱글몰트의 대표 레이블로, 향신료와 단맛의 조화가 또렷하다.",
    priceRange: "₩75,000–100,000", difficulty: "중급", tags: ["싱글몰트", "Indian", "스파이스", "신흥지역"],
  },
  {
    id: "crown-royal-deluxe", name: "Crown Royal Deluxe", distillery: "Crown Royal",
    region: "Manitoba", country: "Canada", category: "기타", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 가벼운 오크", palate: "부드러운 곡물, 토피, 말린과일", finish: "짧고 고소한 여운",
    description: "캐나다 블렌드 특유의 부드러운 질감으로 편하게 즐기기 좋은 위스키.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드", "Canadian", "부드러움", "데일리"],
  },

  // ─── 추가: 블렌디드 스카치 (한국 인기·프리미엄) ───
  {
    id: "johnnie-walker-black", name: "Johnnie Walker Black Label 12", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "건과일, 바닐라, 은은한 스모크", palate: "몰트 단맛, 토피, 가벼운 스파이스", finish: "부드럽고 따뜻하게 이어지는 스모키함",
    description: "스코틀랜드 4개 지역 원액을 12년 이상 숙성해 블렌딩한 균형 잡힌 대중적 스카치.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "12년", "균형감"],
  },
  {
    id: "johnnie-walker-blue", name: "Johnnie Walker Blue Label", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "스카치", age: null, abv: 40,
    nose: "건과일, 헤이즐넛, 시트러스와 옅은 스모크", palate: "꿀의 단맛, 카라멜, 다크초콜릿", finish: "벨벳처럼 길고 매끄러운 스모키 여운",
    description: "희귀 원액만 선별해 만든 조니워커 최상위 프리미엄 블렌디드 스카치.",
    priceRange: "₩260,000–340,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "프리미엄", "복합미"],
  },
  {
    id: "johnnie-walker-red", name: "Johnnie Walker Red Label", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "스카치", age: null, abv: 40,
    nose: "시트러스 제스트, 스파이스, 옅은 스모크", palate: "계피, 후추, 몰트 단맛", finish: "스파이시하고 가볍게 스모키한 마무리",
    description: "하이볼과 칵테일에 어울리는 활기차고 스파이시한 입문용 블렌디드 스카치.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "하이볼", "스파이시"],
  },
  {
    id: "ballantines-finest", name: "Ballantine's Finest", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "스카치", age: null, abv: 40,
    nose: "히더 꿀, 사과, 가벼운 스파이스", palate: "밀크초콜릿, 바닐라, 잘 익은 배", finish: "깔끔하고 플로럴한 짧은 마무리",
    description: "40종 이상 원액을 블렌딩해 가볍고 접근성 좋은 입문용 스카치.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "입문", "부드러움"],
  },
  {
    id: "ballantines-17", name: "Ballantine's 17 Year Old", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "스카치", age: 17, abv: 40,
    nose: "바닐라, 오크, 파인애플과 옅은 스모크", palate: "꿀의 단맛, 크리미한 바닐라, 토피", finish: "길고 매끄러우며 은은하게 스모키한 여운",
    description: "밀튼더프 등 핵심 원액을 17년 이상 숙성한 발렌타인의 대표 프리미엄 블렌드.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "프리미엄", "17년"],
  },
  {
    id: "chivas-12", name: "Chivas Regal 12", distillery: "Chivas Brothers",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "허브, 헤더, 잘 익은 멜론과 과수원 과일", palate: "멜론, 몰트 단맛, 가벼운 스파이스", finish: "꿀과 바닐라, 사과의 따뜻한 여운",
    description: "밝고 과일향 도는 부드러움으로 사랑받는 스페이사이드 중심의 12년 블렌드.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "12년", "과일향"],
  },
  {
    id: "chivas-18", name: "Chivas Regal 18", distillery: "Chivas Brothers",
    region: "Speyside", country: "Scotland", category: "스카치", age: 18, abv: 40,
    nose: "오렌지필, 바닐라 퍼지, 건과일과 옅은 스파이스", palate: "마멀레이드, 다크초콜릿, 버터 토피", finish: "길고 균형 잡힌 오크 스파이스 여운",
    description: "다크초콜릿과 건과일의 풍부한 층이 돋보이는 18년 숙성 프리미엄 스카치.",
    priceRange: "₩110,000–150,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "프리미엄", "18년"],
  },
  {
    id: "royal-salute-21", name: "Royal Salute 21 Year Old", distillery: "Chivas Brothers",
    region: "Speyside", country: "Scotland", category: "스카치", age: 21, abv: 40,
    nose: "잘 익은 배, 시트러스, 올드 오크와 꿀", palate: "초콜릿, 건과일, 카라멜, 토스티 오크", finish: "깔끔하고 정제된 길고 우아한 단맛 여운",
    description: "21년 이상 숙성 원액으로 빚은 시바스 브라더스의 최상위 프리미엄 블렌드.",
    priceRange: "₩240,000–320,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "프리미엄", "21년"],
  },

  // ─── 추가: 싱글몰트 스카치 (한국 인기·프리미엄) ───
  {
    id: "singleton-dufftown-12", name: "The Singleton of Dufftown 12", distillery: "Dufftown",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "꿀, 잘 익은 과수원 과일, 구운 견과", palate: "몰트, 오렌지, 코코아, 부드러운 바닐라", finish: "중간 길이, 스파이스와 밀크 초콜릿",
    description: "한국 싱글몰트 베스트셀러로 부드럽고 균형 잡힌 입문용 스페이사이드.",
    priceRange: "₩70,000–95,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "꿀", "부드러움"],
  },
  {
    id: "macallan-double-cask-12", name: "The Macallan Double Cask 12", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "건과일, 바닐라, 시트러스 제스트", palate: "토피, 말린 자두, 스위트 스파이스, 오크", finish: "길고 따뜻하며 달콤한 스파이스 여운",
    description: "아메리칸·유러피언 오크 셰리 캐스크를 함께 쓴 균형형 셰리 싱글몰트.",
    priceRange: "₩105,000–135,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "셰리", "더블캐스크"],
  },
  {
    id: "macallan-18-sherry", name: "The Macallan Sherry Oak 18", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "스카치", age: 18, abv: 43,
    nose: "말린 과일, 생강, 잘 익은 오크", palate: "오렌지, 클로브, 진한 셰리, 다크 초콜릿", finish: "길고 풍부하며 스파이시한 오크 여운",
    description: "올로로소 셰리 시즈닝 오크에서만 18년 숙성한 프리미엄 셰리 싱글몰트.",
    priceRange: "₩450,000–600,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "셰리", "프리미엄"],
  },
  {
    id: "glenfiddich-15", name: "Glenfiddich 15 Solera", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "스카치", age: 15, abv: 40,
    nose: "꿀, 마지팬, 시나몬, 잘 익은 과일", palate: "꿀단지 달콤함, 셰리, 따뜻한 스파이스, 오크", finish: "길고 부드러우며 풍부한 스파이스",
    description: "솔레라 배트에서 숙성·결합해 꿀빛 달콤함이 도드라지는 스페이사이드 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "솔레라", "꿀"],
  },
  {
    id: "glenfiddich-18", name: "Glenfiddich 18", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "스카치", age: 18, abv: 40,
    nose: "잘 익은 사과, 건포도, 오크, 스파이스", palate: "구운 사과, 시나몬, 토피, 묵직한 오크", finish: "길고 따뜻하며 견고한 오크 여운",
    description: "스몰 배치 숙성으로 깊이를 더한 원숙한 프리미엄 스페이사이드.",
    priceRange: "₩150,000–200,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "오크", "프리미엄"],
  },
  {
    id: "glenlivet-18", name: "The Glenlivet 18", distillery: "The Glenlivet",
    region: "Speyside", country: "Scotland", category: "스카치", age: 18, abv: 40,
    nose: "잘 익은 과일, 꿀, 오렌지, 가벼운 오크", palate: "타닌감 있는 오크, 꿀, 허브, 스파이스", finish: "길고 스파이스가 차오르는 여운",
    description: "버번·셰리 캐스크를 조화시킨 균형감 좋은 프리미엄 스페이사이드.",
    priceRange: "₩140,000–190,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "균형감", "프리미엄"],
  },
  {
    id: "aberlour-12", name: "Aberlour 12 Double Cask Matured", distillery: "Aberlour",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "잘 익은 사과, 셰리, 토피, 시나몬", palate: "초콜릿, 달콤한 셰리, 생강, 오크", finish: "스파이시하고 따뜻한 여운",
    description: "올로로소 셰리와 아메리칸 오크를 함께 쓴 셰리 입문 인기 싱글몰트.",
    priceRange: "₩75,000–100,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "셰리", "더블캐스크"],
  },
  {
    id: "aberlour-abunadh", name: "Aberlour A'bunadh", distillery: "Aberlour",
    region: "Speyside", country: "Scotland", category: "스카치", age: null, abv: 60.8,
    nose: "건포도, 다크 초콜릿, 오렌지 마멀레이드", palate: "올로로소 셰리, 무화과, 시나몬", finish: "길고 진한 셰리와 스파이스의 여운",
    description: "퍼스트필 올로로소 셰리 버트에서만 숙성한 캐스크 스트렝스 논칠필터 위스키로, 도수는 배치마다 약 59~61%로 상이하다.",
    priceRange: "₩120,000–160,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "셰리", "캐스크스트렝스"],
  },
  {
    id: "bowmore-12", name: "Bowmore 12", distillery: "Bowmore",
    region: "Islay", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "은은한 피트 스모크, 레몬, 꿀", palate: "스모크, 오렌지, 바닐라", finish: "잔잔한 재와 시트러스의 가벼운 여운",
    description: "부드러운 피트 스모크와 시트러스 단맛이 균형 잡힌 아일라 피트 입문용 싱글몰트.",
    priceRange: "₩60,000–80,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "피트", "스모키"],
  },
  {
    id: "dalmore-12", name: "The Dalmore 12", distillery: "The Dalmore",
    region: "Highland", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "오렌지 제스트, 시나몬, 초콜릿", palate: "셰리, 캔디드 오렌지, 토피", finish: "달콤한 토피와 오크가 길게 이어지는 여운",
    description: "버번과 올로로소 셰리 캐스크에서 숙성해 시트러스와 초콜릿 풍미가 풍부한 하이랜드 싱글몰트.",
    priceRange: "₩80,000–110,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "셰리", "스무스"],
  },
  {
    id: "glenmorangie-lasanta-12", name: "Glenmorangie Lasanta 12", distillery: "Glenmorangie",
    region: "Highland", country: "Scotland", category: "스카치", age: 12, abv: 43,
    nose: "꿀, 초콜릿 입힌 건포도, 보리", palate: "다크 초콜릿, 말린 과일, 토피", finish: "스파이스와 말린 과일 단맛이 따뜻하게 남는 여운",
    description: "버번 캐스크 숙성 후 올로로소·PX 셰리 캐스크에서 마무리해 달콤하고 부드러운 하이랜드 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "셰리피니시", "스무스"],
  },
  {
    id: "balvenie-caribbean-14", name: "The Balvenie Caribbean Cask 14", distillery: "The Balvenie",
    region: "Speyside", country: "Scotland", category: "스카치", age: 14, abv: 43,
    nose: "바닐라, 토피, 열대 과일", palate: "꿀, 바닐라, 망고", finish: "오렌지와 열대 과일이 은은하게 사라지는 여운",
    description: "전통 오크 숙성 후 카리브 럼 캐스크에서 마무리해 열대 과일 단맛이 도는 스페이사이드 싱글몰트.",
    priceRange: "₩110,000–140,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "럼피니시", "트로피컬"],
  },
  {
    id: "ardbeg-uigeadail", name: "Ardbeg Uigeadail", distillery: "Ardbeg",
    region: "Islay", country: "Scotland", category: "스카치", age: null, abv: 54.2,
    nose: "강렬한 피트 스모크, 크리스마스 케이크, 가죽", palate: "달콤한 건포도, 윈터 스파이스, 훈연", finish: "건포도와 모카, 짙은 훈연이 길게 이어지는 여운",
    description: "올로로소 셰리 캐스크 원액을 결합한 캐스크 스트렝스로, 강한 피트와 셰리 단맛이 응축된 아일라 프리미엄 싱글몰트.",
    priceRange: "₩130,000–170,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "캐스크스트렝스"],
  },
  {
    id: "glenfarclas-12", name: "Glenfarclas 12", distillery: "Glenfarclas",
    region: "Speyside", country: "Scotland", category: "스카치", age: 12, abv: 43,
    nose: "올로로소 셰리, 꿀, 오크", palate: "셰리 단맛, 프루트케이크, 건포도", finish: "오렌지와 시나몬, 따뜻한 셰리의 긴 여운",
    description: "올로로소 셰리 캐스크에서 숙성해 견과와 말린 과일, 베이킹 스파이스가 풍부한 스페이사이드 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "셰리", "리치"],
  },

  // ─── 추가: 아이리쉬 ───
  {
    id: "redbreast-15", name: "Redbreast 15", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: 15, abv: 46,
    nose: "베리 과일, 견과 오일, 아로마틱 스파이스", palate: "과즙 풍부한 과일, 스파이스, 토스티드 오크", finish: "길고 정제된 여운에 셰리와 오크",
    description: "버번 배럴과 올로로소 셰리 캐스크에서 15년 숙성한 프리미엄 싱글 팟 스틸 위스키.",
    priceRange: "₩150,000–190,000", difficulty: "중급", tags: ["싱글팟스틸", "Ireland", "셰리캐스크", "프리미엄"],
  },
  {
    id: "jameson-black-barrel", name: "Jameson Black Barrel", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "버터스카치, 토피, 바닐라, 견과", palate: "크리미한 단맛, 스파이스, 바닐라, 견과", finish: "토스티드 오크와 바닐라의 풍부한 여운",
    description: "이중 차링한 배럴에서 숙성한 소량 생산 팟 스틸과 그레인 블렌드.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["블렌디드", "Ireland", "더블차드", "팟스틸"],
  },

  // ─── 추가: 아메리칸 버번/라이 (한국 인기·하이볼·프리미엄) ───
  {
    id: "jack-daniels-old-no7", name: "Jack Daniel's Old No.7", distillery: "Jack Daniel's",
    region: "Tennessee", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 토스티드 오크, 바나나", palate: "스위트 옥수수, 바닐라, 캐러멜, 가벼운 스파이스", finish: "부드럽고 깔끔한 중간 길이 여운",
    description: "사탕단풍 숯으로 여과하는 링컨 카운티 공정을 거친 테네시 위스키의 대표작.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["테네시", "Tennessee", "차콜멜로잉", "베스트셀러"],
  },
  {
    id: "gentleman-jack", name: "Gentleman Jack", distillery: "Jack Daniel's",
    region: "Tennessee", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 꿀, 가벼운 과일", palate: "크리미한 바닐라, 토피, 구운 사과, 시나몬", finish: "비단결처럼 매끄럽고 깔끔한 여운",
    description: "숯 여과를 숙성 전후 두 번 거치는 더블 멜로잉으로 부드러움을 극대화한 테네시 위스키.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["테네시", "Tennessee", "더블멜로잉", "스무스"],
  },
  {
    id: "jim-beam-white", name: "Jim Beam White Label", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 가벼운 오크, 곡물 단맛", palate: "스위트 옥수수, 바닐라, 캐러멜, 가벼운 스파이스", finish: "바닐라와 부드러운 오크의 중간 여운",
    description: "옥수수 단맛과 부드러운 질감으로 하이볼에 두루 쓰이는 대중적인 켄터키 버번.",
    priceRange: "₩30,000–40,000", difficulty: "입문", tags: ["버번", "Kentucky", "하이볼", "데일리"],
  },
  {
    id: "jim-beam-black", name: "Jim Beam Black Extra Aged", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43,
    nose: "캐러멜, 오크, 시나몬, 바닐라", palate: "묵직한 캐러멜, 구운 견과, 우디 차, 바닐라", finish: "우드 스파이스와 토피의 짧고 단정한 여운",
    description: "기본 라인보다 오래 숙성해 더 깊고 묵직한 풍미를 지닌 켄터키 스트레이트 버번.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["버번", "Kentucky", "익스트라에이지드", "풀바디"],
  },
  {
    id: "makers-mark-46", name: "Maker's Mark 46", distillery: "Maker's Mark",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 47,
    nose: "토스티드 프렌치 오크, 캐러멜라이즈드 슈거, 베이킹 스파이스, 바닐라", palate: "버터스카치, 다크 프루트, 시나몬, 토스티드 오크", finish: "스위트 토바코, 코코아, 차드 스파이스의 길고 매끄러운 여운",
    description: "밀 매시빌 버번을 시어드 프렌치 오크 스테이브로 추가 마무리한 진하고 향신료 풍부한 버번.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["버번", "Kentucky", "휘티드", "프렌치오크"],
  },
  {
    id: "blantons-single-barrel", name: "Blanton's Original Single Barrel", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 46.5,
    nose: "바닐라, 캐러멜, 베이킹 스파이스", palate: "감귤, 꿀, 오크, 라이 스파이스", finish: "옥수수와 따뜻한 향신료가 중간 길이로 이어짐",
    description: "버펄로 트레이스의 상징적인 프리미엄 싱글 배럴 버번으로, 균형 잡힌 단맛과 스파이스가 특징이다.",
    priceRange: "₩200,000–250,000", difficulty: "중급", tags: ["버번", "Kentucky", "싱글배럴", "프리미엄"],
  },
  {
    id: "eagle-rare-10", name: "Eagle Rare 10", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 10, abv: 45,
    nose: "토피, 오렌지 껍질, 가죽, 다크 코코아", palate: "캔디드 아몬드, 바닐라, 캐러멜, 베이킹 스파이스", finish: "드라이하고 길게 여운이 남는 마무리",
    description: "10년 숙성한 버펄로 트레이스의 프리미엄 버번으로, 깊은 오크와 코코아 풍미가 돋보인다.",
    priceRange: "₩75,000–90,000", difficulty: "중급", tags: ["버번", "Kentucky", "10년", "프리미엄"],
  },
  {
    id: "woodford-double-oaked", name: "Woodford Reserve Double Oaked", distillery: "Woodford Reserve",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.2,
    nose: "건과일, 오렌지, 코코아, 바닐라", palate: "토피, 캐러멜, 시나몬, 초콜릿", finish: "달콤한 오크와 향신료가 부드럽게 마무리됨",
    description: "두 번째 배럴에서 추가 숙성해 진한 오크와 단맛을 끌어올린 버번.",
    priceRange: "₩100,000–120,000", difficulty: "중급", tags: ["버번", "Kentucky", "더블오크", "스위트"],
  },
  {
    id: "four-roses-small-batch", name: "Four Roses Small Batch", distillery: "Four Roses",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "잘 익은 베리, 바닐라, 캐러멜, 가벼운 오크", palate: "꿀, 베이킹 스파이스, 크리미한 바닐라, 라이 스파이스", finish: "캐러멜과 향신료가 길고 부드럽게 이어짐",
    description: "네 가지 레시피를 블렌딩해 층층이 복합적인 풍미를 보여주는 스몰 배치 버번.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["버번", "Kentucky", "스몰배치", "밸런스"],
  },
  {
    id: "bookers", name: "Booker's Bourbon", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 63,
    nose: "바닐라, 오크, 토피, 가죽", palate: "캐러멜, 다크 초콜릿, 견과류, 진한 오크", finish: "강렬한 스파이스와 오크가 길게 타오르는 마무리",
    description: "여과·가수 없이 배럴 프루프 그대로 병입한 짐 빔의 고도수 버번으로, 도수는 배치마다 약 60~65%로 상이하다.",
    priceRange: "₩130,000–170,000", difficulty: "상급", tags: ["버번", "Kentucky", "배럴프루프", "프리미엄"],
  },
  {
    id: "basil-hayden", name: "Basil Hayden", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "그을린 오크, 바닐라, 복숭아, 화이트 페퍼", palate: "흑설탕, 베리, 검은 후추, 가벼운 민트", finish: "은은한 향신료와 건과일이 깔끔하게 남는 마무리",
    description: "라이 비율을 높여 가볍고 스파이시하면서도 접근하기 쉬운 하이라이 버번.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["버번", "Kentucky", "하이라이", "가벼움"],
  },
  {
    id: "old-forester-100", name: "Old Forester 100 Proof", distillery: "Brown-Forman",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "캐러멜, 다크 초콜릿, 구운 견과류, 토스트 오크", palate: "흑설탕, 사과, 베이킹 스파이스, 그을린 오크", finish: "후추와 정향, 비터스위트 초콜릿이 따뜻하게 이어짐",
    description: "100프루프의 힘 있는 클래식 버번으로, 스파이시한 오크 풍미가 뚜렷하다.",
    priceRange: "₩45,000–60,000", difficulty: "중급", tags: ["버번", "Kentucky", "100프루프", "스파이시"],
  },
  {
    id: "elijah-craig-barrel-proof", name: "Elijah Craig Barrel Proof", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 62.5,
    nose: "캐러멜, 바닐라, 오크, 다크체리", palate: "진한 토피, 계피, 다크초콜릿, 구운 견과", finish: "길고 묵직한 오크와 스파이스 여운",
    description: "연 3회 배치로 출시되는 무가수 배럴 프루프 버번으로, 도수는 배치마다 약 59~65%로 상이하다.",
    priceRange: "₩150,000–220,000", difficulty: "상급", tags: ["버번", "Kentucky", "배럴프루프", "프리미엄"],
  },
  {
    id: "wild-turkey-rare-breed", name: "Wild Turkey Rare Breed", distillery: "Wild Turkey",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 58.4,
    nose: "바닐라, 캐러멜, 오렌지필, 오크", palate: "토피, 후추, 계피, 구운 옥수수", finish: "따뜻하고 스파이시한 긴 여운",
    description: "6·8·12년 원액을 블렌딩한 배럴 프루프 버번으로 높은 도수에도 균형이 좋다.",
    priceRange: "₩100,000–130,000", difficulty: "상급", tags: ["버번", "Kentucky", "배럴프루프", "프리미엄"],
  },
  {
    id: "russells-reserve-10", name: "Russell's Reserve 10", distillery: "Wild Turkey",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 10, abv: 45,
    nose: "캐러멜, 바닐라, 오크, 말린 과일", palate: "토피, 계피, 꿀, 오렌지", finish: "부드럽고 둥근 오크 여운",
    description: "러셀 부자 마스터 디스틸러의 이름을 딴 10년 숙성 스몰 배치 버번.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["버번", "Kentucky", "10년", "스몰배치"],
  },
  {
    id: "michters-us1-bourbon", name: "Michter's US*1 Small Batch Bourbon", distillery: "Michter's",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45.7,
    nose: "캐러멜, 바닐라, 스톤프루트, 베이킹 스파이스", palate: "토피, 다크프루트, 단 옥수수, 은은한 오크", finish: "부드럽게 이어지는 캐러멜과 스파이스 여운",
    description: "최대 20배럴 소량 배치로 병입하는 켄터키 스트레이트 버번.",
    priceRange: "₩110,000–140,000", difficulty: "중급", tags: ["버번", "Kentucky", "스몰배치", "프리미엄"],
  },
  {
    id: "angels-envy", name: "Angel's Envy", distillery: "Angel's Envy",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.3,
    nose: "바닐라, 건포도, 메이플시럽, 구운 견과", palate: "메이플, 잘 익은 과일, 토스트, 비터초콜릿", finish: "부드럽고 달콤한 포트 와인 여운",
    description: "포트 와인 캐스크에 피니시해 달콤하고 둥근 풍미를 지닌 켄터키 스트레이트 버번.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["버번", "Kentucky", "포트캐스크", "프리미엄"],
  },
  {
    id: "sazerac-rye", name: "Sazerac Rye", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "라이 스파이스, 정향, 바닐라, 시트러스", palate: "후추, 계피, 캐러멜, 민트", finish: "스파이시하고 산뜻한 여운",
    description: "버팔로 트레이스가 만드는 켄터키 스트레이트 라이로 산뜻한 향신료 풍미가 돋보인다.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["라이", "Kentucky", "스파이시", "버팔로트레이스"],
  },
  {
    id: "knob-creek-rye", name: "Knob Creek Rye", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "라이 스파이스, 캐러멜, 오크, 바닐라", palate: "계피, 후추, 토피, 민트", finish: "달콤한 배럴과 스파이스가 어우러진 긴 여운",
    description: "100프루프로 병입하는 짐 빔의 켄터키 스트레이트 라이로 향신료와 단맛의 균형이 좋다.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["라이", "Kentucky", "100프루프", "스몰배치"],
  },

  // ─── 추가: 일본 위스키 (하이볼·싱글몰트) ───
  {
    id: "suntory-kakubin", name: "Suntory Kakubin", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: null, abv: 40,
    nose: "레몬, 풋사과, 헤이즐넛", palate: "팝콘, 사과, 구운 아몬드", finish: "건조하고 풀향이 감도는 마무리",
    description: "야마자키·하쿠슈·치타 원액을 블렌딩한 산토리의 대표 입문용 위스키로 하이볼 베이스로 널리 사랑받는다.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "하이볼", "데일리"],
  },
  {
    id: "suntory-chita", name: "Suntory Chita Single Grain", distillery: "Suntory",
    region: "Aichi", country: "Japan", category: "기타", age: null, abv: 43,
    nose: "바닐라, 꿀, 장미", palate: "바나나, 복숭아, 버터스카치", finish: "백후추와 오크가 가볍게 드라이하게 떨어지는 마무리",
    description: "산토리 치타 증류소의 싱글 그레인으로 부드럽고 깔끔해 하이볼에 잘 어울리는 위스키.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["싱글그레인", "Japanese", "하이볼", "부드러움"],
  },
  {
    id: "nikka-yoichi", name: "Nikka Yoichi Single Malt", distillery: "Yoichi",
    region: "Hokkaido", country: "Japan", category: "기타", age: null, abv: 45,
    nose: "은은한 피트 연기, 오렌지 껍질, 멜론", palate: "흙내 피트, 커피, 토피", finish: "연기와 열대과일이 길게 이어지는 마무리",
    description: "석탄 직화 증류와 이시카리만 해풍이 빚어낸 홋카이도 요이치 증류소의 묵직하고 스모키한 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "피트", "스모키"],
  },
  {
    id: "nikka-miyagikyo", name: "Nikka Miyagikyo Single Malt", distillery: "Miyagikyo",
    region: "Miyagi", country: "Japan", category: "기타", age: null, abv: 45,
    nose: "사과, 배, 꽃향", palate: "귤, 바나나, 바닐라", finish: "은은한 과일향과 가는 탄닌이 길게 남는 마무리",
    description: "증기 간접 가열 증류로 화사한 과일향이 돋보이는 미야기쿄 증류소의 우아한 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "프루티", "셰리"],
  },

  // ─── 추가 2차: 블렌디드 스카치 (지역·클래식·프리미엄 보강) ───
  {
    id: "johnnie-walker-green", name: "Johnnie Walker Green Label 15", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "스카치", age: 15, abv: 43,
    nose: "에스프레소, 우드스모크, 비터초콜릿", palate: "곡물, 커피빈, 대추야자", finish: "길고 스파이시한 꿀과 오크",
    description: "크라간모어·링크우드·카올일라·탈리스커 네 싱글몰트를 블렌딩한 15년 블렌디드 몰트.",
    priceRange: "₩70,000–90,000", difficulty: "중급", tags: ["블렌디드몰트", "Scotch", "스모키", "몰티"],
  },
  {
    id: "dewars-12", name: "Dewar's 12", distillery: "Dewar's",
    region: "Multiple", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "꿀, 열대과일, 바닐라", palate: "배, 복숭아, 너트맥", finish: "오크와 꿀의 부드러운 여운",
    description: "더블 에이징으로 마무리해 부드러움을 강조한 12년 블렌디드 스카치.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "부드러움", "더블에이징"],
  },
  {
    id: "famous-grouse", name: "The Famous Grouse", distillery: "The Famous Grouse",
    region: "Multiple", country: "Scotland", category: "스카치", age: null, abv: 40,
    nose: "토피애플, 비스킷 보리, 시트러스필", palate: "크리미한 몰트, 약한 스파이스, 옅은 스모크", finish: "달콤하고 몰티한 균형 잡힌 마무리",
    description: "스코틀랜드 국민 위스키로 불리는 대중적인 입문용 블렌디드 스카치.",
    priceRange: "₩30,000–40,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "대중적", "균형"],
  },
  {
    id: "old-parr-12", name: "Old Parr 12", distillery: "Old Parr",
    region: "Multiple", country: "Scotland", category: "스카치", age: 12, abv: 40,
    nose: "꿀, 쇼트브레드, 몰티 시리얼", palate: "꿀, 건과일, 은은한 피트", finish: "레몬그라스와 페퍼리한 스파이스의 긴 여운",
    description: "꿀과 은은한 스모크가 어우러진, 한국에서 오랜 인기를 누린 12년 블렌디드 스카치.",
    priceRange: "₩50,000–65,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "꿀", "몰티"],
  },
  {
    id: "ballantines-21", name: "Ballantine's 21 Year Old", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "스카치", age: 21, abv: 40,
    nose: "꿀, 바닐라, 화이트초콜릿", palate: "정향, 너트맥, 캐러멜 퍼지", finish: "스무스한 스파이스와 꿀의 긴 여운",
    description: "유러피언 오크 비중을 높여 풍부함을 더한 21년 숙성 프리미엄 블렌디드 스카치.",
    priceRange: "₩280,000–350,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "프리미엄", "장기숙성"],
  },

  // ─── 추가 2차: 싱글몰트 스카치 (지역 다양성·프리미엄 보강) ───
  {
    id: "glenlivet-15", name: "The Glenlivet 15 French Oak Reserve", distillery: "The Glenlivet",
    region: "Speyside", country: "Scotland", category: "스카치", age: 15, abv: 40,
    nose: "파인애플, 꿀, 바닐라", palate: "정향, 너트, 건포도, 오크 스파이스", finish: "꿀과 시나몬의 중간 길이 피니쉬",
    description: "리무진 프렌치 오크에서 추가 숙성해 부드러운 스파이스와 견과류 풍미를 더한 스페이사이드 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "프렌치오크", "부드러움"],
  },
  {
    id: "highland-park-18", name: "Highland Park 18 Viking Pride", distillery: "Highland Park",
    region: "Highland (Orkney)", country: "Scotland", category: "스카치", age: 18, abv: 43,
    nose: "성숙한 오크, 꿀, 말린 과일, 은은한 히더 피트 스모크", palate: "캔디드 오렌지, 꿀, 체리, 코코아, 겨울 스파이스", finish: "부드럽고 둥근 긴 피니쉬",
    description: "셰리 숙성과 오크니 특유의 히더 피트가 균형을 이룬 프리미엄 싱글몰트.",
    priceRange: "₩280,000–350,000", difficulty: "상급", tags: ["싱글몰트", "Orkney", "셰리", "프리미엄"],
  },
  {
    id: "lagavulin-8", name: "Lagavulin 8", distillery: "Lagavulin",
    region: "Islay", country: "Scotland", category: "스카치", age: 8, abv: 48,
    nose: "키퍼 피트, 짭짤한 소금기, 요오드, 잘 익은 배", palate: "묵직한 스모크, 훈제 생선, 사과 껍질, 단 몰트", finish: "길고 건조한 재 같은 피니쉬",
    description: "비교적 어린 숙성에도 라가불린 특유의 강렬한 피트와 짠맛이 살아있는 아일라 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "스모키"],
  },
  {
    id: "laphroaig-quarter-cask", name: "Laphroaig Quarter Cask", distillery: "Laphroaig",
    region: "Islay", country: "Scotland", category: "스카치", age: null, abv: 48,
    nose: "약품 피트, 요오드, 단 시리얼, 감초", palate: "강한 피트, 바닐라, 보리 단맛, 오크, 후추 스파이스", finish: "피트와 스모크, 오크가 길게 이어지는 피니쉬",
    description: "쿼터 캐스크 추가 숙성으로 오크 접촉을 극대화해 진하고 강렬한 피트를 끌어낸 아일라 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "쿼터캐스크", "강한피트"],
  },
  {
    id: "glendronach-18", name: "The GlenDronach 18 Allardice", distillery: "The GlenDronach",
    region: "Highland", country: "Scotland", category: "스카치", age: 18, abv: 46,
    nose: "올로로소 셰리, 대추, 건포도, 다크초콜릿, 크리스마스 스파이스", palate: "셰리 단맛, 스튜 과일, 코코아, 오렌지 필, 토스트 호두", finish: "셰리와 다크 프루트, 스파이스가 길게 남는 피니쉬",
    description: "올로로소 셰리 캐스크에서 18년 숙성해 진한 다크 프루트와 초콜릿 풍미가 가득한 프리미엄 하이랜드 싱글몰트.",
    priceRange: "₩190,000–260,000", difficulty: "상급", tags: ["싱글몰트", "Highland", "올로로소셰리", "프리미엄"],
  },
  {
    id: "glenkinchie-12", name: "Glenkinchie 12", distillery: "Glenkinchie",
    region: "Lowland", country: "Scotland", category: "스카치", age: 12, abv: 43,
    nose: "레몬, 풋사과, 꿀, 바닐라, 풀향", palate: "풋과일, 보리 몰트, 코코아, 가벼운 스파이스", finish: "시트러스와 풋사과가 깔끔하게 떨어지는 피니쉬",
    description: "가볍고 산뜻한 풀향과 시트러스가 돋보이는 로우랜드 대표 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "입문", tags: ["싱글몰트", "Lowland", "가벼움", "입문용"],
  },
  {
    id: "caol-ila-12", name: "Caol Ila 12", distillery: "Caol Ila",
    region: "Islay", country: "Scotland", category: "스카치", age: 12, abv: 43,
    nose: "바다 소금, 풀향, 훈제 고기, 시트러스, 오일리한 스모크", palate: "오일리한 타르, 우아한 스모크, 브라인, 가벼운 스파이스", finish: "후추 같은 스파이스와 스모크가 길게 이어지는 피니쉬",
    description: "묵직하지 않으면서 깔끔한 스모크와 바다 향이 균형 잡힌 접근성 좋은 아일라 싱글몰트.",
    priceRange: "₩80,000–110,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "스모키", "해풍"],
  },
  {
    id: "clynelish-14", name: "Clynelish 14", distillery: "Clynelish",
    region: "Highland", country: "Scotland", category: "스카치", age: 14, abv: 46,
    nose: "꿀, 바닐라, 배, 사과, 특유의 왁시함", palate: "오일리하고 왁시한 질감, 버터스카치, 배, 토피", finish: "스파이스와 꿀, 플로럴함이 길게 남는 피니쉬",
    description: "특유의 왁시한 질감과 꿀, 과일 풍미가 어우러진 하이랜드 코스탈 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "왁시", "꿀"],
  },
];

export const CATEGORY_TO_TYPE: Record<string, string> = {
  "스카치": "Scotch",
  "아이리쉬": "Irish",
  "버번/라이": "Bourbon/Rye",
  "기타": "Etc",
};
