export interface EncyclopediaEntry {
  id: string;
  name: string;
  distillery: string;
  region: string;
  country: string;
  category: string;
  age: number | null;
  abv: number;
  nose: string;
  palate: string;
  finish: string;
  description: string;
  priceRange: string;
  difficulty: "입문" | "중급" | "상급";
  tags: string[];
}

export const ENCYCLOPEDIA_WHISKEYS: EncyclopediaEntry[] = [
  {
    id: "glenlivet-12", name: "글렌리벳 12년", distillery: "The Glenlivet",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "꽃향, 바닐라, 열대과일", palate: "부드러운 오크, 파인애플, 복숭아", finish: "가볍고 달콤한 여운",
    description: "스피사이드를 대표하는 입문용 싱글몰트. 깔끔하고 달콤한 풍미로 위스키 입문자에게 추천.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "달콤함", "입문추천"],
  },
  {
    id: "glenfiddich-12", name: "글렌피딕 12년", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "신선한 배, 크리미한 토피", palate: "배, 오크, 은은한 스파이스", finish: "부드럽고 짧은 여운",
    description: "세계에서 가장 많이 팔리는 싱글몰트. 접근성이 좋고 균형 잡힌 맛.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "과일향", "입문추천"],
  },
  {
    id: "macallan-12", name: "맥캘란 12년 셰리 오크", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "건포도, 무화과, 진저", palate: "풍부한 셰리, 초콜릿, 오렌지 껍질", finish: "길고 따뜻한 스파이시 여운",
    description: "셰리 오크 캐스크의 정수. 달콤하고 과일향 풍부한 스피사이드 대표작.",
    priceRange: "₩90,000–120,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "셰리캐스크", "초콜릿"],
  },
  {
    id: "lagavulin-16", name: "라가불린 16년", distillery: "Lagavulin",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 16, abv: 43,
    nose: "강렬한 피트, 바다소금, 스모키", palate: "두꺼운 피트, 스위트몰트, 아이오딘", finish: "매우 길고 드라이한 스모키 여운",
    description: "아일라 피트 위스키의 교과서. 강렬하고 복잡한 스모키 풍미의 정점.",
    priceRange: "₩100,000–140,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "스모키", "강렬함"],
  },
  {
    id: "laphroaig-10", name: "라프로익 10년", distillery: "Laphroaig",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 10, abv: 40,
    nose: "병원 소독약, 해초, 피트", palate: "스모키, 달콤함, 소금기", finish: "길고 드라이, 약품향 여운",
    description: "좋아하거나 싫어하거나. 아이오딘과 피트의 극단적 조합으로 독보적 개성.",
    priceRange: "₩55,000–75,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "아이오딘", "개성강함"],
  },
  {
    id: "highland-park-12", name: "하이랜드 파크 12년", distillery: "Highland Park",
    region: "Highland (Orkney)", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "꿀, 헤더, 은은한 피트", palate: "과일, 스파이스, 부드러운 스모키", finish: "균형 잡힌 달콤함과 피트 여운",
    description: "피트와 달콤함의 완벽한 균형. 오크니 섬의 바이킹 정신을 담은 위스키.",
    priceRange: "₩55,000–70,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "밸런스", "꿀향"],
  },
  {
    id: "oban-14", name: "오반 14년", distillery: "Oban",
    region: "West Highland", country: "Scotland", category: "싱글몰트", age: 14, abv: 43,
    nose: "바다소금, 꿀, 은은한 피트", palate: "드라이한 오크, 견과류, 과일향", finish: "따뜻하고 긴 스파이시 여운",
    description: "하이랜드와 아일라의 중간 지점. 해양성과 달콤함이 조화로운 명작.",
    priceRange: "₩80,000–105,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "해양성", "균형"],
  },
  {
    id: "glenmorangie-10", name: "글렌모렌지 오리지널 10년", distillery: "Glenmorangie",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 10, abv: 40,
    nose: "복숭아, 오렌지, 레몬그라스", palate: "바닐라, 크림, 복숭아", finish: "길고 부드러운 달콤한 여운",
    description: "높은 증류기에서 나오는 섬세한 풍미. 화사한 꽃향과 과일향의 하이랜드 입문작.",
    priceRange: "₩55,000–70,000", difficulty: "입문", tags: ["싱글몰트", "Highland", "꽃향", "과일향"],
  },
  {
    id: "jameson", name: "제임슨 오리지널", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "가벼운 스파이스, 맥아, 나무향", palate: "부드러운 그레인, 바닐라, 견과류", finish: "깔끔하고 짧은 여운",
    description: "세계에서 가장 많이 팔리는 아이리쉬 위스키. 트리플 디스틸드의 부드러움.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "부드러움", "입문추천"],
  },
  {
    id: "redbreast-12", name: "레드브레스트 12년", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: 12, abv: 40,
    nose: "셰리, 건포도, 향신료", palate: "풍부한 과일, 스파이스, 초콜릿", finish: "길고 따뜻한 스파이시 여운",
    description: "아이리쉬 팟 스틸의 정수. 풍부하고 복잡한 풍미로 아이리쉬 프리미엄 대표작.",
    priceRange: "₩65,000–85,000", difficulty: "중급", tags: ["팟스틸", "아이리쉬", "셰리캐스크", "프리미엄"],
  },
  {
    id: "green-spot", name: "그린 스팟", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "신선한 사과, 보리, 스파이스", palate: "크리미, 사과, 허브", finish: "부드럽고 스파이시한 여운",
    description: "전통 팟 스틸 스타일의 희귀 아이리쉬. 과거 와인 상인들이 비축했던 스타일 재현.",
    priceRange: "₩60,000–80,000", difficulty: "중급", tags: ["팟스틸", "아이리쉬", "희귀", "전통"],
  },
  {
    id: "bushmills-original", name: "부쉬밀 오리지널", distillery: "Old Bushmills",
    region: "County Antrim", country: "Northern Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "꿀, 사과, 가벼운 바닐라", palate: "달콤한 과일, 몰트, 가벼운 스파이스", finish: "부드럽고 짧은 여운",
    description: "세계에서 가장 오래된 면허 증류소. 가볍고 달콤한 블렌디드 입문작.",
    priceRange: "₩30,000–45,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "달콤함", "역사"],
  },
  {
    id: "buffalo-trace", name: "버팔로 트레이스", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "바닐라, 민트, 갈색설탕", palate: "카라멜, 바닐라, 오크", finish: "오래 지속되는 달콤한 여운",
    description: "가격 대비 품질이 뛰어난 켄터키 버번의 기준점. 부드럽고 균형 잡힌 클래식.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["버번", "Kentucky", "바닐라", "입문추천"],
  },
  {
    id: "makers-mark", name: "메이커스 마크", distillery: "Maker's Mark",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "달콤한 맥아, 바닐라, 꿀", palate: "카라멜, 버터, 부드러운 스파이스", finish: "달콤하고 따뜻한 여운",
    description: "밀 매시빌로 만든 부드러운 버번. 빨간 왁스 인장으로 유명한 아이콘.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["버번", "Kentucky", "부드러움", "밀매시빌"],
  },
  {
    id: "woodford-reserve", name: "우드포드 리저브", distillery: "Woodford Reserve",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.2,
    nose: "초콜릿, 건과일, 오렌지", palate: "풍부한 과일, 스파이스, 오크", finish: "길고 따뜻한 스파이시 여운",
    description: "트리플 디스틸드 켄터키 버번. 복잡하고 세련된 풍미로 프리미엄 버번 대표작.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["버번", "Kentucky", "트리플디스틸드", "프리미엄"],
  },
  {
    id: "wild-turkey-101", name: "와일드 터키 101", distillery: "Wild Turkey",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50.5,
    nose: "카라멜, 바닐라, 오크", palate: "진한 캐러멜, 스파이스, 오렌지", finish: "강렬하고 긴 스파이시 여운",
    description: "101 프루프의 강렬한 버번. 오크통 풍미가 진하고 개성 넘치는 하이프루프 스탠다드.",
    priceRange: "₩40,000–55,000", difficulty: "중급", tags: ["버번", "Kentucky", "하이프루프", "강렬함"],
  },
  {
    id: "rittenhouse-rye", name: "리튼하우스 라이", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "호밀빵, 민트, 스파이스", palate: "진한 스파이스, 후추, 달콤함", finish: "드라이하고 긴 스파이시 여운",
    description: "가성비 최고의 라이 위스키. 칵테일 베이스로도, 스트레이트로도 탁월.",
    priceRange: "₩35,000–50,000", difficulty: "중급", tags: ["라이", "Pennsylvania", "스파이시", "칵테일"],
  },
  {
    id: "bulleit-bourbon", name: "불렛 버번", distillery: "Bulleit Distilling Co. (Diageo)",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "오크, 메이플시럽, 향신료", palate: "매운 호밀향, 바닐라, 오렌지껍질", finish: "드라이하고 길게 지속되는 스파이시",
    description: "높은 라이 함량으로 스파이시한 개성. 심플한 병 디자인과 탄탄한 맛.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["버번", "Kentucky", "하이라이", "스파이시"],
  },
  {
    id: "yamazaki-12", name: "야마자키 12년", distillery: "Yamazaki",
    region: "Osaka", country: "Japan", category: "기타", age: 12, abv: 43,
    nose: "복숭아, 파인애플, 생강", palate: "달콤한 오크, 코코넛, 미즈나라", finish: "길고 드라이하며 스파이시",
    description: "일본 위스키의 상징. 미즈나라 오크의 독특한 향과 동양적 감성의 정점.",
    priceRange: "₩150,000–250,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "미즈나라", "프리미엄"],
  },
  {
    id: "nikka-from-barrel", name: "닛카 프롬 더 배럴", distillery: "Nikka",
    region: "Hokkaido / Miyagi", country: "Japan", category: "기타", age: null, abv: 51.4,
    nose: "캐러멜, 건포도, 바닐라", palate: "풍부한 오크, 과일, 스파이스", finish: "길고 복잡한 따뜻한 여운",
    description: "가성비 최고의 일본 블렌디드. 고도수에서 오는 묵직함과 복잡함이 특징.",
    priceRange: "₩60,000–85,000", difficulty: "중급", tags: ["블렌디드", "Japanese", "하이프루프", "가성비"],
  },
  {
    id: "kavalan-classic", name: "카발란 클래식", distillery: "Kavalan",
    region: "Yilan", country: "Taiwan", category: "기타", age: null, abv: 40,
    nose: "트로피컬 과일, 바닐라, 복숭아", palate: "달콤한 오크, 망고, 코코넛", finish: "부드럽고 달콤한 여운",
    description: "대만의 아열대 기후가 만들어내는 빠른 숙성의 트로피컬 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "입문", tags: ["싱글몰트", "Taiwanese", "트로피컬", "달콤함"],
  },
  {
    id: "hibiki-harmony", name: "히비키 재패니즈 하모니", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: null, abv: 43,
    nose: "로즈우드, 감귤, 꿀", palate: "오렌지껍질, 달콤한 오크, 화이트초콜릿", finish: "길고 향기로운 여운",
    description: "산토리의 블렌딩 철학 집대성. 24개 면의 병처럼 24절기를 담은 하모니.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["블렌디드", "Japanese", "꽃향", "프리미엄"],
  },
  {
    id: "talisker-10", name: "탈리스커 10년", distillery: "Talisker",
    region: "Isle of Skye", country: "Scotland", category: "싱글몰트", age: 10, abv: 45.8,
    nose: "후추, 해풍, 스모키", palate: "몰트 단맛, 바다소금, 페퍼", finish: "따뜻하고 후추가 남는 긴 여운",
    description: "스카이 섬 특유의 해양성과 페퍼 스파이스가 선명한 싱글몰트.",
    priceRange: "₩75,000–95,000", difficulty: "중급", tags: ["싱글몰트", "Island", "해양성", "페퍼"],
  },
  {
    id: "glendronach-12", name: "글렌드로낙 12년", distillery: "The GlenDronach",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "셰리, 건과일, 오렌지", palate: "건포도, 토피, 다크초콜릿", finish: "달콤하고 묵직한 셰리 여운",
    description: "올로로소/페드로 히메네즈 셰리 캐스크 숙성의 클래식한 하이랜드 스타일.",
    priceRange: "₩85,000–110,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "셰리캐스크", "건과일"],
  },
  {
    id: "balvenie-doublewood-12", name: "발베니 더블우드 12년", distillery: "The Balvenie",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "꿀, 견과류, 말린과일", palate: "바닐라, 오크, 은은한 시나몬", finish: "부드럽고 달콤한 오크 여운",
    description: "버번 캐스크 후 셰리 캐스크 피니시로 균형감이 뛰어난 스페이사이드 대표작.",
    priceRange: "₩95,000–120,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "더블우드", "밸런스"],
  },
  {
    id: "monkey-shoulder", name: "몽키 숄더", distillery: "William Grant & Sons",
    region: "Speyside", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "바닐라, 오렌지, 몰트", palate: "크리미한 토피, 꿀, 스파이스", finish: "가볍고 산뜻한 달콤함",
    description: "칵테일과 스트레이트 모두 부담 없이 즐기기 좋은 블렌디드 몰트.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드몰트", "Speyside", "칵테일", "입문추천"],
  },
  {
    id: "ardbeg-10", name: "아드벡 10년", distillery: "Ardbeg",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 10, abv: 46,
    nose: "강한 피트, 레몬, 해초", palate: "스모키, 바닐라, 블랙페퍼", finish: "길고 드라이한 피트 여운",
    description: "아일라 피트의 개성을 또렷하게 보여주는 강렬한 싱글몰트.",
    priceRange: "₩80,000–105,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "피트", "스모키"],
  },
  {
    id: "teeling-small-batch", name: "틸링 스몰 배치", distillery: "Teeling",
    region: "Dublin", country: "Ireland", category: "아이리쉬", age: null, abv: 46,
    nose: "런던드라이 과일, 바닐라, 향신료", palate: "럼 캐스크의 달콤함, 오크, 후추", finish: "달콤하고 스파이시한 여운",
    description: "럼 캐스크 피니시가 개성을 더하는 현대적인 더블린 스타일 아이리쉬.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["블렌디드", "아이리쉬", "럼캐스크", "스파이시"],
  },
  {
    id: "writers-tears-copper-pot", name: "라이터즈 티어스 코퍼 팟", distillery: "Walsh Whiskey",
    region: "County Carlow", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "배, 사과, 꿀", palate: "부드러운 몰트, 바닐라, 은은한 오크", finish: "깔끔하고 고소한 여운",
    description: "싱글몰트와 싱글팟스틸 조합으로 부드럽고 우아한 과일향이 돋보인다.",
    priceRange: "₩50,000–70,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "과일향", "부드러움"],
  },
  {
    id: "tullamore-dew", name: "털러모어 듀", distillery: "Tullamore",
    region: "County Offaly", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "레몬 제스트, 바닐라, 시리얼", palate: "가벼운 몰트, 꿀, 스파이스", finish: "짧고 깔끔한 곡물 여운",
    description: "가볍고 산뜻한 스타일로 하이볼이나 데일리 드링크에 잘 맞는 아이리쉬.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "하이볼", "데일리"],
  },
  {
    id: "powers-gold-label", name: "파워스 골드 라벨", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 43.2,
    nose: "시나몬, 꿀, 곡물", palate: "오일리한 질감, 스파이스, 토피", finish: "따뜻하고 드라이한 향신료 여운",
    description: "전통적인 아이리쉬 스파이스가 살아있는 클래식 블렌드.",
    priceRange: "₩45,000–65,000", difficulty: "중급", tags: ["블렌디드", "아이리쉬", "스파이시", "클래식"],
  },
  {
    id: "bushmills-10", name: "부쉬밀 10년", distillery: "Old Bushmills",
    region: "County Antrim", country: "Northern Ireland", category: "아이리쉬", age: 10, abv: 40,
    nose: "꿀, 바닐라, 잘 익은 과일", palate: "밀크초콜릿, 몰트, 사과", finish: "부드럽고 은은한 단맛",
    description: "셰리/버번 캐스크의 균형으로 입문자에게 편안한 10년 숙성 싱글몰트.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["싱글몰트", "아이리쉬", "10년", "입문추천"],
  },
  {
    id: "four-roses-single-barrel", name: "포 로지스 싱글 배럴", distillery: "Four Roses",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "체리, 바닐라, 오크", palate: "카라멜, 후추, 잘 익은 과일", finish: "길고 스파이시한 버번 여운",
    description: "싱글 배럴 특유의 농도와 향신료감이 살아있는 프리미엄 버번.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["버번", "Kentucky", "싱글배럴", "스파이시"],
  },
  {
    id: "knob-creek-9", name: "놉 크릭 9년", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 9, abv: 50,
    nose: "바닐라, 구운오크, 땅콩", palate: "묵직한 캐러멜, 시나몬, 오크", finish: "길고 따뜻한 오크 스파이스",
    description: "9년 숙성과 100프루프 바디감으로 클래식한 풀바디 버번을 보여준다.",
    priceRange: "₩60,000–85,000", difficulty: "중급", tags: ["버번", "Kentucky", "100프루프", "풀바디"],
  },
  {
    id: "elijah-craig-small-batch", name: "일라이저 크레이그 스몰 배치", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 47,
    nose: "토피, 오렌지, 오크", palate: "바닐라, 넛맥, 캐러멜", finish: "중간 길이의 달콤한 스파이스",
    description: "버번의 밸런스를 잘 보여주는 스몰 배치 스타일의 스테디셀러.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["버번", "Kentucky", "스몰배치", "밸런스"],
  },
  {
    id: "evan-williams-single-barrel", name: "에반 윌리엄스 싱글 배럴", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.3,
    nose: "사과, 토피, 바닐라", palate: "오크, 시나몬, 라이트 초콜릿", finish: "부드럽고 은은한 단맛",
    description: "부담 없는 가격대에서 싱글 배럴 개성을 체험하기 좋은 버번.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["버번", "Kentucky", "싱글배럴", "가성비"],
  },
  {
    id: "bulleit-rye", name: "불렛 라이", distillery: "MGP",
    region: "Indiana", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "민트, 딜, 시트러스", palate: "라이 스파이스, 꿀, 오크", finish: "드라이하고 선명한 허브 여운",
    description: "칵테일 베이스로 특히 인기가 높은 스파이시한 라이 위스키.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["라이", "Indiana", "칵테일", "스파이시"],
  },
  {
    id: "hakushu-12", name: "하쿠슈 12년", distillery: "Hakushu",
    region: "Yamanashi", country: "Japan", category: "기타", age: 12, abv: 43,
    nose: "허브, 청사과, 은은한 스모크", palate: "민트, 배, 가벼운 오크", finish: "맑고 시원한 허벌 여운",
    description: "산림 증류소의 청량한 스타일을 보여주는 일본 싱글몰트 대표작.",
    priceRange: "₩200,000–320,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "허브", "프리미엄"],
  },
  {
    id: "suntory-toki", name: "산토리 도키", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: null, abv: 43,
    nose: "바질, 청사과, 꿀", palate: "가벼운 바닐라, 시트러스, 곡물", finish: "짧고 깨끗한 여운",
    description: "하이볼 친화적인 라이트 블렌드로 일본 위스키 입문에 적합하다.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "하이볼", "입문추천"],
  },
  {
    id: "nikka-days", name: "닛카 데이즈", distillery: "Nikka",
    region: "Hokkaido / Miyagi", country: "Japan", category: "기타", age: null, abv: 40,
    nose: "시리얼, 바닐라, 가벼운 과일", palate: "부드러운 몰트, 배, 토피", finish: "은은하고 매끈한 여운",
    description: "데일리 음용을 겨냥한 가벼운 스타일의 일본 블렌디드 위스키.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "데일리", "부드러움"],
  },
  {
    id: "paul-john-brilliance", name: "폴 존 브릴리언스", distillery: "Paul John",
    region: "Goa", country: "India", category: "기타", age: null, abv: 46,
    nose: "꿀, 오렌지 필, 바닐라", palate: "보리 단맛, 시나몬, 견과류", finish: "따뜻하고 스파이시한 여운",
    description: "인도 싱글몰트의 대표 레이블로, 향신료와 단맛의 조화가 또렷하다.",
    priceRange: "₩75,000–100,000", difficulty: "중급", tags: ["싱글몰트", "Indian", "스파이스", "신흥지역"],
  },
  {
    id: "crown-royal-deluxe", name: "크라운 로얄 디럭스", distillery: "Crown Royal",
    region: "Manitoba", country: "Canada", category: "기타", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 가벼운 오크", palate: "부드러운 곡물, 토피, 말린과일", finish: "짧고 고소한 여운",
    description: "캐나다 블렌드 특유의 부드러운 질감으로 편하게 즐기기 좋은 위스키.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드", "Canadian", "부드러움", "데일리"],
  },

  // ─── 추가: 블렌디드 스카치 (한국 인기·프리미엄) ───
  {
    id: "johnnie-walker-black", name: "조니워커 블랙 라벨 12년", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 12, abv: 40,
    nose: "건과일, 바닐라, 은은한 스모크", palate: "몰트 단맛, 토피, 가벼운 스파이스", finish: "부드럽고 따뜻하게 이어지는 스모키함",
    description: "스코틀랜드 4개 지역 원액을 12년 이상 숙성해 블렌딩한 균형 잡힌 대중적 스카치.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "12년", "균형감"],
  },
  {
    id: "johnnie-walker-blue", name: "조니워커 블루 라벨", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "건과일, 헤이즐넛, 시트러스와 옅은 스모크", palate: "꿀의 단맛, 카라멜, 다크초콜릿", finish: "벨벳처럼 길고 매끄러운 스모키 여운",
    description: "희귀 원액만 선별해 만든 조니워커 최상위 프리미엄 블렌디드 스카치.",
    priceRange: "₩260,000–340,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "프리미엄", "복합미"],
  },
  {
    id: "johnnie-walker-red", name: "조니워커 레드 라벨", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "시트러스 제스트, 스파이스, 옅은 스모크", palate: "계피, 후추, 몰트 단맛", finish: "스파이시하고 가볍게 스모키한 마무리",
    description: "하이볼과 칵테일에 어울리는 활기차고 스파이시한 입문용 블렌디드 스카치.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "하이볼", "스파이시"],
  },
  {
    id: "ballantines-finest", name: "발렌타인 파이니스트", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "히더 꿀, 사과, 가벼운 스파이스", palate: "밀크초콜릿, 바닐라, 잘 익은 배", finish: "깔끔하고 플로럴한 짧은 마무리",
    description: "40종 이상 원액을 블렌딩해 가볍고 접근성 좋은 입문용 스카치.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "입문", "부드러움"],
  },
  {
    id: "ballantines-17", name: "발렌타인 17년", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 17, abv: 40,
    nose: "바닐라, 오크, 파인애플과 옅은 스모크", palate: "꿀의 단맛, 크리미한 바닐라, 토피", finish: "길고 매끄러우며 은은하게 스모키한 여운",
    description: "밀튼더프 등 핵심 원액을 17년 이상 숙성한 발렌타인의 대표 프리미엄 블렌드.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "프리미엄", "17년"],
  },
  {
    id: "chivas-12", name: "시바스 리갈 12년", distillery: "Chivas Brothers",
    region: "Speyside", country: "Scotland", category: "블렌디드", age: 12, abv: 40,
    nose: "허브, 헤더, 잘 익은 멜론과 과수원 과일", palate: "멜론, 몰트 단맛, 가벼운 스파이스", finish: "꿀과 바닐라, 사과의 따뜻한 여운",
    description: "밝고 과일향 도는 부드러움으로 사랑받는 스페이사이드 중심의 12년 블렌드.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "12년", "과일향"],
  },
  {
    id: "chivas-18", name: "시바스 리갈 18년", distillery: "Chivas Brothers",
    region: "Speyside", country: "Scotland", category: "블렌디드", age: 18, abv: 40,
    nose: "오렌지필, 바닐라 퍼지, 건과일과 옅은 스파이스", palate: "마멀레이드, 다크초콜릿, 버터 토피", finish: "길고 균형 잡힌 오크 스파이스 여운",
    description: "다크초콜릿과 건과일의 풍부한 층이 돋보이는 18년 숙성 프리미엄 스카치.",
    priceRange: "₩110,000–150,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "프리미엄", "18년"],
  },
  {
    id: "royal-salute-21", name: "로얄 살루트 21년", distillery: "Chivas Brothers",
    region: "Speyside", country: "Scotland", category: "블렌디드", age: 21, abv: 40,
    nose: "잘 익은 배, 시트러스, 올드 오크와 꿀", palate: "초콜릿, 건과일, 카라멜, 토스티 오크", finish: "깔끔하고 정제된 길고 우아한 단맛 여운",
    description: "21년 이상 숙성 원액으로 빚은 시바스 브라더스의 최상위 프리미엄 블렌드.",
    priceRange: "₩240,000–320,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "프리미엄", "21년"],
  },

  // ─── 추가: 싱글몰트 스카치 (한국 인기·프리미엄) ───
  {
    id: "singleton-dufftown-12", name: "싱글턴 오브 더프타운 12년", distillery: "Dufftown",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "꿀, 잘 익은 과수원 과일, 구운 견과", palate: "몰트, 오렌지, 코코아, 부드러운 바닐라", finish: "중간 길이, 스파이스와 밀크 초콜릿",
    description: "한국 싱글몰트 베스트셀러로 부드럽고 균형 잡힌 입문용 스페이사이드.",
    priceRange: "₩70,000–95,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "꿀", "부드러움"],
  },
  {
    id: "macallan-double-cask-12", name: "맥캘란 더블 캐스크 12년", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "건과일, 바닐라, 시트러스 제스트", palate: "토피, 말린 자두, 스위트 스파이스, 오크", finish: "길고 따뜻하며 달콤한 스파이스 여운",
    description: "아메리칸·유러피언 오크 셰리 캐스크를 함께 쓴 균형형 셰리 싱글몰트.",
    priceRange: "₩105,000–135,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "셰리", "더블캐스크"],
  },
  {
    id: "macallan-18-sherry", name: "맥캘란 셰리 오크 18년", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 18, abv: 43,
    nose: "말린 과일, 생강, 잘 익은 오크", palate: "오렌지, 클로브, 진한 셰리, 다크 초콜릿", finish: "길고 풍부하며 스파이시한 오크 여운",
    description: "올로로소 셰리 시즈닝 오크에서만 18년 숙성한 프리미엄 셰리 싱글몰트.",
    priceRange: "₩450,000–600,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "셰리", "프리미엄"],
  },
  {
    id: "glenfiddich-15", name: "글렌피딕 15년 솔레라", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 15, abv: 40,
    nose: "꿀, 마지팬, 시나몬, 잘 익은 과일", palate: "꿀단지 달콤함, 셰리, 따뜻한 스파이스, 오크", finish: "길고 부드러우며 풍부한 스파이스",
    description: "솔레라 배트에서 숙성·결합해 꿀빛 달콤함이 도드라지는 스페이사이드 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "솔레라", "꿀"],
  },
  {
    id: "glenfiddich-18", name: "글렌피딕 18년", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 18, abv: 40,
    nose: "잘 익은 사과, 건포도, 오크, 스파이스", palate: "구운 사과, 시나몬, 토피, 묵직한 오크", finish: "길고 따뜻하며 견고한 오크 여운",
    description: "스몰 배치 숙성으로 깊이를 더한 원숙한 프리미엄 스페이사이드.",
    priceRange: "₩150,000–200,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "오크", "프리미엄"],
  },
  {
    id: "glenlivet-18", name: "글렌리벳 18년", distillery: "The Glenlivet",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 18, abv: 40,
    nose: "잘 익은 과일, 꿀, 오렌지, 가벼운 오크", palate: "타닌감 있는 오크, 꿀, 허브, 스파이스", finish: "길고 스파이스가 차오르는 여운",
    description: "버번·셰리 캐스크를 조화시킨 균형감 좋은 프리미엄 스페이사이드.",
    priceRange: "₩140,000–190,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "균형감", "프리미엄"],
  },
  {
    id: "aberlour-12", name: "아벨라워 12년 더블 캐스크", distillery: "Aberlour",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "잘 익은 사과, 셰리, 토피, 시나몬", palate: "초콜릿, 달콤한 셰리, 생강, 오크", finish: "스파이시하고 따뜻한 여운",
    description: "올로로소 셰리와 아메리칸 오크를 함께 쓴 셰리 입문 인기 싱글몰트.",
    priceRange: "₩75,000–100,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "셰리", "더블캐스크"],
  },
  {
    id: "aberlour-abunadh", name: "아벨라워 아부나흐", distillery: "Aberlour",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: null, abv: 60.8,
    nose: "건포도, 다크 초콜릿, 오렌지 마멀레이드", palate: "올로로소 셰리, 무화과, 시나몬", finish: "길고 진한 셰리와 스파이스의 여운",
    description: "퍼스트필 올로로소 셰리 버트에서만 숙성한 캐스크 스트렝스 논칠필터 위스키로, 도수는 배치마다 약 59~61%로 상이하다.",
    priceRange: "₩120,000–160,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "셰리", "캐스크스트렝스"],
  },
  {
    id: "bowmore-12", name: "보모어 12년", distillery: "Bowmore",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "은은한 피트 스모크, 레몬, 꿀", palate: "스모크, 오렌지, 바닐라", finish: "잔잔한 재와 시트러스의 가벼운 여운",
    description: "부드러운 피트 스모크와 시트러스 단맛이 균형 잡힌 아일라 피트 입문용 싱글몰트.",
    priceRange: "₩60,000–80,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "피트", "스모키"],
  },
  {
    id: "dalmore-12", name: "달모어 12년", distillery: "The Dalmore",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "오렌지 제스트, 시나몬, 초콜릿", palate: "셰리, 캔디드 오렌지, 토피", finish: "달콤한 토피와 오크가 길게 이어지는 여운",
    description: "버번과 올로로소 셰리 캐스크에서 숙성해 시트러스와 초콜릿 풍미가 풍부한 하이랜드 싱글몰트.",
    priceRange: "₩80,000–110,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "셰리", "스무스"],
  },
  {
    id: "glenmorangie-lasanta-12", name: "글렌모렌지 라산타 12년", distillery: "Glenmorangie",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "꿀, 초콜릿 입힌 건포도, 보리", palate: "다크 초콜릿, 말린 과일, 토피", finish: "스파이스와 말린 과일 단맛이 따뜻하게 남는 여운",
    description: "버번 캐스크 숙성 후 올로로소·PX 셰리 캐스크에서 마무리해 달콤하고 부드러운 하이랜드 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "셰리피니시", "스무스"],
  },
  {
    id: "balvenie-caribbean-14", name: "발베니 캐리비안 캐스크 14년", distillery: "The Balvenie",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 14, abv: 43,
    nose: "바닐라, 토피, 열대 과일", palate: "꿀, 바닐라, 망고", finish: "오렌지와 열대 과일이 은은하게 사라지는 여운",
    description: "전통 오크 숙성 후 카리브 럼 캐스크에서 마무리해 열대 과일 단맛이 도는 스페이사이드 싱글몰트.",
    priceRange: "₩110,000–140,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "럼피니시", "트로피컬"],
  },
  {
    id: "ardbeg-uigeadail", name: "아드벡 우거다일", distillery: "Ardbeg",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: null, abv: 54.2,
    nose: "강렬한 피트 스모크, 크리스마스 케이크, 가죽", palate: "달콤한 건포도, 윈터 스파이스, 훈연", finish: "건포도와 모카, 짙은 훈연이 길게 이어지는 여운",
    description: "올로로소 셰리 캐스크 원액을 결합한 캐스크 스트렝스로, 강한 피트와 셰리 단맛이 응축된 아일라 프리미엄 싱글몰트.",
    priceRange: "₩130,000–170,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "캐스크스트렝스"],
  },
  {
    id: "glenfarclas-12", name: "글렌파클라스 12년", distillery: "Glenfarclas",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "올로로소 셰리, 꿀, 오크", palate: "셰리 단맛, 프루트케이크, 건포도", finish: "오렌지와 시나몬, 따뜻한 셰리의 긴 여운",
    description: "올로로소 셰리 캐스크에서 숙성해 견과와 말린 과일, 베이킹 스파이스가 풍부한 스페이사이드 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "셰리", "리치"],
  },

  // ─── 추가: 아이리쉬 ───
  {
    id: "redbreast-15", name: "레드브레스트 15년", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: 15, abv: 46,
    nose: "베리 과일, 견과 오일, 아로마틱 스파이스", palate: "과즙 풍부한 과일, 스파이스, 토스티드 오크", finish: "길고 정제된 여운에 셰리와 오크",
    description: "버번 배럴과 올로로소 셰리 캐스크에서 15년 숙성한 프리미엄 싱글 팟 스틸 위스키.",
    priceRange: "₩150,000–190,000", difficulty: "중급", tags: ["싱글팟스틸", "Ireland", "셰리캐스크", "프리미엄"],
  },
  {
    id: "jameson-black-barrel", name: "제임슨 블랙 배럴", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "버터스카치, 토피, 바닐라, 견과", palate: "크리미한 단맛, 스파이스, 바닐라, 견과", finish: "토스티드 오크와 바닐라의 풍부한 여운",
    description: "이중 차링한 배럴에서 숙성한 소량 생산 팟 스틸과 그레인 블렌드.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["블렌디드", "Ireland", "더블차드", "팟스틸"],
  },

  // ─── 추가: 아메리칸 버번/라이 (한국 인기·하이볼·프리미엄) ───
  {
    id: "jack-daniels-old-no7", name: "잭 다니엘스 올드 No.7", distillery: "Jack Daniel's",
    region: "Tennessee", country: "USA", category: "테네시", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 토스티드 오크, 바나나", palate: "스위트 옥수수, 바닐라, 캐러멜, 가벼운 스파이스", finish: "부드럽고 깔끔한 중간 길이 여운",
    description: "사탕단풍 숯으로 여과하는 링컨 카운티 공정을 거친 테네시 위스키의 대표작.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["테네시", "Tennessee", "차콜멜로잉", "베스트셀러"],
  },
  {
    id: "gentleman-jack", name: "젠틀맨 잭", distillery: "Jack Daniel's",
    region: "Tennessee", country: "USA", category: "테네시", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 꿀, 가벼운 과일", palate: "크리미한 바닐라, 토피, 구운 사과, 시나몬", finish: "비단결처럼 매끄럽고 깔끔한 여운",
    description: "숯 여과를 숙성 전후 두 번 거치는 더블 멜로잉으로 부드러움을 극대화한 테네시 위스키.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["테네시", "Tennessee", "더블멜로잉", "스무스"],
  },
  {
    id: "jim-beam-white", name: "짐 빔 화이트 라벨", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "바닐라, 캐러멜, 가벼운 오크, 곡물 단맛", palate: "스위트 옥수수, 바닐라, 캐러멜, 가벼운 스파이스", finish: "바닐라와 부드러운 오크의 중간 여운",
    description: "옥수수 단맛과 부드러운 질감으로 하이볼에 두루 쓰이는 대중적인 켄터키 버번.",
    priceRange: "₩30,000–40,000", difficulty: "입문", tags: ["버번", "Kentucky", "하이볼", "데일리"],
  },
  {
    id: "jim-beam-black", name: "짐 빔 블랙 엑스트라 에이지드", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43,
    nose: "캐러멜, 오크, 시나몬, 바닐라", palate: "묵직한 캐러멜, 구운 견과, 우디 차, 바닐라", finish: "우드 스파이스와 토피의 짧고 단정한 여운",
    description: "기본 라인보다 오래 숙성해 더 깊고 묵직한 풍미를 지닌 켄터키 스트레이트 버번.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["버번", "Kentucky", "익스트라에이지드", "풀바디"],
  },
  {
    id: "makers-mark-46", name: "메이커스 마크 46", distillery: "Maker's Mark",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 47,
    nose: "토스티드 프렌치 오크, 캐러멜라이즈드 슈거, 베이킹 스파이스, 바닐라", palate: "버터스카치, 다크 프루트, 시나몬, 토스티드 오크", finish: "스위트 토바코, 코코아, 차드 스파이스의 길고 매끄러운 여운",
    description: "밀 매시빌 버번을 시어드 프렌치 오크 스테이브로 추가 마무리한 진하고 향신료 풍부한 버번.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["버번", "Kentucky", "휘티드", "프렌치오크"],
  },
  {
    id: "blantons-single-barrel", name: "블랑톤 오리지널 싱글 배럴", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 46.5,
    nose: "바닐라, 캐러멜, 베이킹 스파이스", palate: "감귤, 꿀, 오크, 라이 스파이스", finish: "옥수수와 따뜻한 향신료가 중간 길이로 이어짐",
    description: "버펄로 트레이스의 상징적인 프리미엄 싱글 배럴 버번으로, 균형 잡힌 단맛과 스파이스가 특징이다.",
    priceRange: "₩200,000–250,000", difficulty: "중급", tags: ["버번", "Kentucky", "싱글배럴", "프리미엄"],
  },
  {
    id: "eagle-rare-10", name: "이글 레어 10년", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 10, abv: 45,
    nose: "토피, 오렌지 껍질, 가죽, 다크 코코아", palate: "캔디드 아몬드, 바닐라, 캐러멜, 베이킹 스파이스", finish: "드라이하고 길게 여운이 남는 마무리",
    description: "10년 숙성한 버펄로 트레이스의 프리미엄 버번으로, 깊은 오크와 코코아 풍미가 돋보인다.",
    priceRange: "₩75,000–90,000", difficulty: "중급", tags: ["버번", "Kentucky", "10년", "프리미엄"],
  },
  {
    id: "woodford-double-oaked", name: "우드포드 리저브 더블 오크드", distillery: "Woodford Reserve",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.2,
    nose: "건과일, 오렌지, 코코아, 바닐라", palate: "토피, 캐러멜, 시나몬, 초콜릿", finish: "달콤한 오크와 향신료가 부드럽게 마무리됨",
    description: "두 번째 배럴에서 추가 숙성해 진한 오크와 단맛을 끌어올린 버번.",
    priceRange: "₩100,000–120,000", difficulty: "중급", tags: ["버번", "Kentucky", "더블오크", "스위트"],
  },
  {
    id: "four-roses-small-batch", name: "포 로지스 스몰 배치", distillery: "Four Roses",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "잘 익은 베리, 바닐라, 캐러멜, 가벼운 오크", palate: "꿀, 베이킹 스파이스, 크리미한 바닐라, 라이 스파이스", finish: "캐러멜과 향신료가 길고 부드럽게 이어짐",
    description: "네 가지 레시피를 블렌딩해 층층이 복합적인 풍미를 보여주는 스몰 배치 버번.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["버번", "Kentucky", "스몰배치", "밸런스"],
  },
  {
    id: "bookers", name: "부커스 버번", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 63,
    nose: "바닐라, 오크, 토피, 가죽", palate: "캐러멜, 다크 초콜릿, 견과류, 진한 오크", finish: "강렬한 스파이스와 오크가 길게 타오르는 마무리",
    description: "여과·가수 없이 배럴 프루프 그대로 병입한 짐 빔의 고도수 버번으로, 도수는 배치마다 약 60~65%로 상이하다.",
    priceRange: "₩130,000–170,000", difficulty: "상급", tags: ["버번", "Kentucky", "배럴프루프", "프리미엄"],
  },
  {
    id: "basil-hayden", name: "베이즐 헤이든", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "그을린 오크, 바닐라, 복숭아, 화이트 페퍼", palate: "흑설탕, 베리, 검은 후추, 가벼운 민트", finish: "은은한 향신료와 건과일이 깔끔하게 남는 마무리",
    description: "라이 비율을 높여 가볍고 스파이시하면서도 접근하기 쉬운 하이라이 버번.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["버번", "Kentucky", "하이라이", "가벼움"],
  },
  {
    id: "old-forester-100", name: "올드 포레스터 100 프루프", distillery: "Brown-Forman",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "캐러멜, 다크 초콜릿, 구운 견과류, 토스트 오크", palate: "흑설탕, 사과, 베이킹 스파이스, 그을린 오크", finish: "후추와 정향, 비터스위트 초콜릿이 따뜻하게 이어짐",
    description: "100프루프의 힘 있는 클래식 버번으로, 스파이시한 오크 풍미가 뚜렷하다.",
    priceRange: "₩45,000–60,000", difficulty: "중급", tags: ["버번", "Kentucky", "100프루프", "스파이시"],
  },
  {
    id: "elijah-craig-barrel-proof", name: "일라이저 크레이그 배럴 프루프", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 62.5,
    nose: "캐러멜, 바닐라, 오크, 다크체리", palate: "진한 토피, 계피, 다크초콜릿, 구운 견과", finish: "길고 묵직한 오크와 스파이스 여운",
    description: "연 3회 배치로 출시되는 무가수 배럴 프루프 버번으로, 도수는 배치마다 약 59~65%로 상이하다.",
    priceRange: "₩150,000–220,000", difficulty: "상급", tags: ["버번", "Kentucky", "배럴프루프", "프리미엄"],
  },
  {
    id: "wild-turkey-rare-breed", name: "와일드 터키 레어 브리드", distillery: "Wild Turkey",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 58.4,
    nose: "바닐라, 캐러멜, 오렌지필, 오크", palate: "토피, 후추, 계피, 구운 옥수수", finish: "따뜻하고 스파이시한 긴 여운",
    description: "6·8·12년 원액을 블렌딩한 배럴 프루프 버번으로 높은 도수에도 균형이 좋다.",
    priceRange: "₩100,000–130,000", difficulty: "상급", tags: ["버번", "Kentucky", "배럴프루프", "프리미엄"],
  },
  {
    id: "russells-reserve-10", name: "러셀 리저브 10년", distillery: "Wild Turkey",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 10, abv: 45,
    nose: "캐러멜, 바닐라, 오크, 말린 과일", palate: "토피, 계피, 꿀, 오렌지", finish: "부드럽고 둥근 오크 여운",
    description: "러셀 부자 마스터 디스틸러의 이름을 딴 10년 숙성 스몰 배치 버번.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["버번", "Kentucky", "10년", "스몰배치"],
  },
  {
    id: "michters-us1-bourbon", name: "믹터스 US*1 스몰 배치 버번", distillery: "Michter's",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45.7,
    nose: "캐러멜, 바닐라, 스톤프루트, 베이킹 스파이스", palate: "토피, 다크프루트, 단 옥수수, 은은한 오크", finish: "부드럽게 이어지는 캐러멜과 스파이스 여운",
    description: "최대 20배럴 소량 배치로 병입하는 켄터키 스트레이트 버번.",
    priceRange: "₩110,000–140,000", difficulty: "중급", tags: ["버번", "Kentucky", "스몰배치", "프리미엄"],
  },
  {
    id: "angels-envy", name: "엔젤스 엔비", distillery: "Angel's Envy",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 43.3,
    nose: "바닐라, 건포도, 메이플시럽, 구운 견과", palate: "메이플, 잘 익은 과일, 토스트, 비터초콜릿", finish: "부드럽고 달콤한 포트 와인 여운",
    description: "포트 와인 캐스크에 피니시해 달콤하고 둥근 풍미를 지닌 켄터키 스트레이트 버번.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["버번", "Kentucky", "포트캐스크", "프리미엄"],
  },
  {
    id: "sazerac-rye", name: "사제락 라이", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "라이 스파이스, 정향, 바닐라, 시트러스", palate: "후추, 계피, 캐러멜, 민트", finish: "스파이시하고 산뜻한 여운",
    description: "버팔로 트레이스가 만드는 켄터키 스트레이트 라이로 산뜻한 향신료 풍미가 돋보인다.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["라이", "Kentucky", "스파이시", "버팔로트레이스"],
  },
  {
    id: "knob-creek-rye", name: "놉 크릭 라이", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 7, abv: 50,
    nose: "라이 스파이스, 캐러멜, 오크, 바닐라", palate: "계피, 후추, 토피, 민트", finish: "달콤한 배럴과 스파이스가 어우러진 긴 여운",
    description: "100프루프로 병입하는 짐 빔의 켄터키 스트레이트 라이로 향신료와 단맛의 균형이 좋다.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["라이", "Kentucky", "100프루프", "스몰배치"],
  },

  // ─── 추가: 일본 위스키 (하이볼·싱글몰트) ───
  {
    id: "suntory-kakubin", name: "산토리 가쿠빈", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: null, abv: 40,
    nose: "레몬, 풋사과, 헤이즐넛", palate: "팝콘, 사과, 구운 아몬드", finish: "건조하고 풀향이 감도는 마무리",
    description: "야마자키·하쿠슈·치타 원액을 블렌딩한 산토리의 대표 입문용 위스키로 하이볼 베이스로 널리 사랑받는다.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "하이볼", "데일리"],
  },
  {
    id: "suntory-chita", name: "산토리 치타 싱글 그레인", distillery: "Suntory",
    region: "Aichi", country: "Japan", category: "기타", age: null, abv: 43,
    nose: "바닐라, 꿀, 장미", palate: "바나나, 복숭아, 버터스카치", finish: "백후추와 오크가 가볍게 드라이하게 떨어지는 마무리",
    description: "산토리 치타 증류소의 싱글 그레인으로 부드럽고 깔끔해 하이볼에 잘 어울리는 위스키.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["싱글그레인", "Japanese", "하이볼", "부드러움"],
  },
  {
    id: "nikka-yoichi", name: "닛카 요이치 싱글몰트", distillery: "Yoichi",
    region: "Hokkaido", country: "Japan", category: "기타", age: null, abv: 45,
    nose: "은은한 피트 연기, 오렌지 껍질, 멜론", palate: "흙내 피트, 커피, 토피", finish: "연기와 열대과일이 길게 이어지는 마무리",
    description: "석탄 직화 증류와 이시카리만 해풍이 빚어낸 홋카이도 요이치 증류소의 묵직하고 스모키한 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "피트", "스모키"],
  },
  {
    id: "nikka-miyagikyo", name: "닛카 미야기쿄 싱글몰트", distillery: "Miyagikyo",
    region: "Miyagi", country: "Japan", category: "기타", age: null, abv: 45,
    nose: "사과, 배, 꽃향", palate: "귤, 바나나, 바닐라", finish: "은은한 과일향과 가는 탄닌이 길게 남는 마무리",
    description: "증기 간접 가열 증류로 화사한 과일향이 돋보이는 미야기쿄 증류소의 우아한 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Japanese", "프루티", "셰리"],
  },

  // ─── 추가 2차: 블렌디드 스카치 (지역·클래식·프리미엄 보강) ───
  {
    id: "johnnie-walker-green", name: "조니워커 그린 라벨 15년", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 15, abv: 43,
    nose: "에스프레소, 우드스모크, 비터초콜릿", palate: "곡물, 커피빈, 대추야자", finish: "길고 스파이시한 꿀과 오크",
    description: "크라간모어·링크우드·카올일라·탈리스커 네 싱글몰트를 블렌딩한 15년 블렌디드 몰트.",
    priceRange: "₩70,000–90,000", difficulty: "중급", tags: ["블렌디드몰트", "Scotch", "스모키", "몰티"],
  },
  {
    id: "dewars-12", name: "듀어스 12년", distillery: "Dewar's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 12, abv: 40,
    nose: "꿀, 열대과일, 바닐라", palate: "배, 복숭아, 너트맥", finish: "오크와 꿀의 부드러운 여운",
    description: "더블 에이징으로 마무리해 부드러움을 강조한 12년 블렌디드 스카치.",
    priceRange: "₩45,000–60,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "부드러움", "더블에이징"],
  },
  {
    id: "famous-grouse", name: "페이머스 그라우스", distillery: "The Famous Grouse",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "토피애플, 비스킷 보리, 시트러스필", palate: "크리미한 몰트, 약한 스파이스, 옅은 스모크", finish: "달콤하고 몰티한 균형 잡힌 마무리",
    description: "스코틀랜드 국민 위스키로 불리는 대중적인 입문용 블렌디드 스카치.",
    priceRange: "₩30,000–40,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "대중적", "균형"],
  },
  {
    id: "old-parr-12", name: "올드 파 12년", distillery: "Old Parr",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 12, abv: 40,
    nose: "꿀, 쇼트브레드, 몰티 시리얼", palate: "꿀, 건과일, 은은한 피트", finish: "레몬그라스와 페퍼리한 스파이스의 긴 여운",
    description: "꿀과 은은한 스모크가 어우러진, 한국에서 오랜 인기를 누린 12년 블렌디드 스카치.",
    priceRange: "₩50,000–65,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "꿀", "몰티"],
  },
  {
    id: "ballantines-21", name: "발렌타인 21년", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 21, abv: 40,
    nose: "꿀, 바닐라, 화이트초콜릿", palate: "정향, 너트맥, 캐러멜 퍼지", finish: "스무스한 스파이스와 꿀의 긴 여운",
    description: "유러피언 오크 비중을 높여 풍부함을 더한 21년 숙성 프리미엄 블렌디드 스카치.",
    priceRange: "₩280,000–350,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "프리미엄", "장기숙성"],
  },

  // ─── 추가 4차: 블렌디드 스카치 (클래식·프리미엄·블렌디드 몰트 보강) ───
  {
    id: "johnnie-walker-double-black", name: "조니워커 더블 블랙", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "달콤한 연기, 정향, 바닐라", palate: "피트 스모크, 말린 과일, 오렌지 제스트, 바닐라", finish: "따뜻한 스모크가 길게 이어지는 마무리",
    description: "강한 피트 캐릭터와 깊게 그을린 오크 캐스크를 활용해 블랙 라벨보다 스모키한 풍미를 강조한 블렌디드 스카치.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "피트", "스모키"],
  },
  {
    id: "johnnie-walker-gold-label-reserve", name: "조니워커 골드 라벨 리저브", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "꿀, 바닐라, 은은한 꽃향", palate: "달콤한 과일, 크리미한 토피, 꿀", finish: "가벼운 스모크와 단맛의 매끄러운 여운",
    description: "달콤한 꿀의 풍미와 부드러운 질감을 중심으로 설계한 조니워커의 프리미엄 블렌디드 스카치.",
    priceRange: "₩75,000–105,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "꿀", "프리미엄"],
  },
  {
    id: "chivas-xv", name: "시바스 리갈 XV", distillery: "Chivas Brothers",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 15, abv: 40,
    nose: "조린 붉은 사과, 오렌지 마멀레이드, 꿀, 시나몬, 건포도", palate: "포치드 페어, 버터스카치, 캐러멜 토피", finish: "둥글고 부드러운 꿀의 여운",
    description: "최소 15년 숙성한 원액 일부를 그랑 샹파뉴 코냑 캐스크에서 선택적으로 피니시해 풍부한 과일과 단맛을 더한 블렌디드 스카치.",
    priceRange: "₩80,000–110,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "코냑캐스크", "15년"],
  },
  {
    id: "dewars-15", name: "듀어스 15년", distillery: "Dewar's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 15, abv: 40,
    nose: "꿀, 과일, 바닐라, 꽃향", palate: "풋사과, 시트러스, 토피, 견과류", finish: "부드럽고 은은한 스모크의 여운",
    description: "최대 30종의 몰트와 그레인 원액을 블렌딩하고 더블 에이징해 매끄러운 질감과 꿀 풍미를 살린 15년 블렌디드 스카치.",
    priceRange: "₩65,000–90,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "더블에이징", "15년"],
  },
  {
    id: "dewars-18", name: "듀어스 18년", distillery: "Dewar's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 18, abv: 40,
    nose: "마지팬, 꿀, 토피, 다크초콜릿", palate: "꽃향, 견과류, 익은 과일, 크리미한 오크", finish: "허브와 오크가 부드럽고 길게 남는 마무리",
    description: "18년 이상 숙성한 몰트와 그레인 원액을 더블 에이징해 풍부함과 부드러움을 함께 끌어낸 프리미엄 블렌디드 스카치.",
    priceRange: "₩95,000–130,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "더블에이징", "18년"],
  },
  {
    id: "buchanans-deluxe-12", name: "뷰캐넌스 디럭스 12년", distillery: "Buchanan's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 12, abv: 40,
    nose: "신선한 과일, 오렌지, 가벼운 몰트", palate: "부드러운 과일, 오렌지, 밀크초콜릿", finish: "달콤하고 매끄러운 중간 길이의 여운",
    description: "부드럽고 신선한 과일 풍미에 오렌지와 초콜릿 뉘앙스가 어우러지는 12년 블렌디드 스카치.",
    priceRange: "₩55,000–80,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "12년", "프루티"],
  },
  {
    id: "grants-triple-wood", name: "그란츠 트리플 우드", distillery: "William Grant & Sons",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "잘 익은 배, 여름 과일", palate: "바닐라, 몰트, 꽃향, 흑설탕", finish: "달콤하고 옅은 스모크가 남는 긴 여운",
    description: "버진 오크·아메리칸 오크·리필 버번 캐스크의 서로 다른 특성을 조합한 부드러운 블렌디드 스카치.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "트리플우드", "가성비"],
  },
  {
    id: "cutty-sark-original", name: "커티 삭 오리지널", distillery: "Cutty Sark",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "가벼운 꽃향, 과수원 과일, 시트러스", palate: "바닐라, 시트러스, 부드러운 곡물", finish: "깨끗하고 산뜻한 짧은 여운",
    description: "몰트와 그레인 원액을 가볍고 신선한 스타일로 블렌딩해 하이볼과 칵테일에도 잘 어울리는 클래식 스카치.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "라이트", "하이볼"],
  },
  {
    id: "teachers-highland-cream", name: "티처스 하이랜드 크림", distillery: "Teacher's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "피트 스모크, 잘 익은 사과, 배", palate: "달콤한 곡물, 몰트, 부드러운 과일", finish: "풍부한 스모크 뒤로 산뜻하게 떨어지는 마무리",
    description: "아드모어의 스모키한 몰트를 핵심 원액으로 삼아 피트와 부드러운 단맛의 균형을 살린 블렌디드 스카치.",
    priceRange: "₩22,000–32,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "피트", "가성비"],
  },
  {
    id: "compass-box-orchard-house", name: "컴파스 박스 오차드 하우스", distillery: "Compass Box",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 46,
    nose: "사과, 배, 파인애플, 레몬, 얼그레이", palate: "과수원 과일, 몰트, 생강, 꿀", finish: "딸기와 바닐라 쇼트브레드의 산뜻한 여운",
    description: "과수원 과일 캐릭터가 선명한 싱글몰트 원액만을 블렌딩하고 내추럴 컬러·논칠필터로 병입한 블렌디드 몰트 스카치.",
    priceRange: "₩85,000–115,000", difficulty: "중급", tags: ["블렌디드몰트", "Scotch", "프루티", "논칠필터"],
  },
  {
    id: "compass-box-peat-monster", name: "컴파스 박스 더 피트 몬스터", distillery: "Compass Box",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 46,
    nose: "바닷물, 향신료를 더한 사과, 바닐라, 달콤한 연기", palate: "피트 스모크, 크리미한 과일, 몰트", finish: "바다 내음과 스모크가 길고 균형 있게 이어지는 마무리",
    description: "아일라 싱글몰트를 중심으로 달콤한 연기와 무거운 피트를 균형 있게 조합한 내추럴 컬러·논칠필터 블렌디드 몰트.",
    priceRange: "₩95,000–125,000", difficulty: "상급", tags: ["블렌디드몰트", "Scotch", "피트", "논칠필터"],
  },

  // ─── 추가 5차: 주요 블렌디드 브랜드 및 발렌타인 라인업 보강 ───
  {
    id: "ballantines-7-american-barrel", name: "발렌타인 7년 아메리칸 배럴", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 7, abv: 40,
    nose: "토피를 입힌 붉은 사과, 황금빛 꿀, 바닐라", palate: "잘 익은 배, 붉은 사과, 크리미한 캐러멜", finish: "달콤하고 길게 이어지는 여운",
    description: "7년 숙성한 블렌드를 아메리칸 오크 캐스크로 마무리해 사과와 캐러멜의 단맛을 강조한 발렌타인.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "아메리칸오크", "7년"],
  },
  {
    id: "ballantines-10", name: "발렌타인 10년", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 10, abv: 40,
    nose: "달콤한 꿀, 오크, 바닐라", palate: "복합적인 꿀, 꽃향, 크리미한 오크", finish: "산뜻하고 달콤하게 오래 남는 마무리",
    description: "마스터 블렌더가 선별한 원액을 10년 이상 숙성해 꿀 향과 크리미한 오크 단맛의 균형을 살린 블렌디드 스카치.",
    priceRange: "₩45,000–65,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "꿀", "10년"],
  },
  {
    id: "ballantines-12", name: "발렌타인 12년", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 12, abv: 40,
    nose: "꿀, 붉은 사과, 바닐라, 꽃향", palate: "익은 과일, 꿀, 크리미한 오크, 은은한 향신료", finish: "오크와 꿀이 부드럽게 이어지는 여운",
    description: "최소 12년 숙성한 몰트와 그레인 원액으로 발렌타인 특유의 꿀·과일·바닐라 균형을 보여주는 클래식 블렌드.",
    priceRange: "₩50,000–70,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "12년", "클래식"],
  },
  {
    id: "ballantines-23", name: "발렌타인 23년", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 23, abv: 40,
    nose: "꿀 시럽을 두른 배, 크리미한 바닐라, 붉은 사과, 시나몬", palate: "진한 과수원 과일, 포치드 페어, 바닐라 크림", finish: "매우 길고 부드러우며 달콤한 여운",
    description: "23년 이상 숙성한 원액으로 풍성한 과수원 과일과 겹겹의 향신료, 새틴처럼 매끄러운 질감을 구현한 프리미엄 블렌드.",
    priceRange: "₩280,000–400,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "23년", "프리미엄"],
  },
  {
    id: "ballantines-30", name: "발렌타인 30년", distillery: "Ballantine's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 30, abv: 40,
    nose: "깊고 부드러운 과일, 우아한 단맛, 바닐라 오크", palate: "꿀, 꽃향, 배, 복숭아, 바닐라", finish: "우아하고 매우 길게 지속되는 여운",
    description: "일부 폐쇄 증류소의 희귀 원액을 포함해 최소 30년 숙성한 위스키로 만든 발렌타인의 최고급 장기 숙성 블렌드.",
    priceRange: "₩500,000–800,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "30년", "울트라프리미엄"],
  },
  {
    id: "johnnie-walker-18", name: "조니워커 18년", distillery: "Johnnie Walker",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 18, abv: 40,
    nose: "달콤한 과일, 부드러운 향신료, 바닐라", palate: "다크초콜릿, 익은 과일, 크리미한 몰트", finish: "카듀의 크리미함과 은은한 스파이스가 길게 이어지는 마무리",
    description: "블레어 아톨의 향신료, 글렌 엘긴의 달콤한 과일, 카듀의 크리미함을 중심으로 구성한 18년 블렌디드 스카치.",
    priceRange: "₩130,000–180,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "18년", "다크초콜릿"],
  },
  {
    id: "chivas-mizunara", name: "시바스 리갈 미즈나라", distillery: "Chivas Brothers",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "배, 오렌지, 풍부한 과일, 은은한 꽃향", palate: "꿀, 헤이즐넛, 부드러운 오크", finish: "미즈나라 향신료가 또렷하게 남는 마무리",
    description: "블렌드 일부를 희귀한 일본산 미즈나라 오크 캐스크에서 선택적으로 피니시해 섬세한 꽃향과 향신료를 더한 스카치.",
    priceRange: "₩80,000–120,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "미즈나라", "캐스크피니시"],
  },
  {
    id: "chivas-25", name: "시바스 리갈 25년", distillery: "Chivas Brothers",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 25, abv: 40,
    nose: "달콤한 오렌지, 복숭아, 마지팬, 견과류", palate: "리치한 초콜릿 오렌지, 퐁당 크림", finish: "매끄럽고 둥글며 호화롭게 긴 여운",
    description: "모든 원액이 25년 이상 숙성되며 각 캐스크를 개별 선별해 만드는 시바스의 역사적인 럭셔리 블렌디드 스카치.",
    priceRange: "₩400,000–600,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "25년", "울트라프리미엄"],
  },
  {
    id: "royal-salute-32", name: "로얄 살루트 32년 더 프레셔스 주얼", distillery: "Chivas Brothers",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 32, abv: 40,
    nose: "시럽에 담근 복숭아, 캐러멜 토피, 시나몬, 다크초콜릿", palate: "오렌지, 잘 익은 배, 촉촉한 진저 케이크", finish: "끝없이 이어지는 풍부하고 우아한 여운",
    description: "스코틀랜드 여러 지역의 희귀 원액을 최소 32년 숙성해 왕실의 보석에서 영감을 받은 도자기 병에 담은 최고급 블렌드.",
    priceRange: "₩700,000–1,000,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "32년", "울트라프리미엄"],
  },
  {
    id: "dewars-white-label", name: "듀어스 화이트 라벨", distillery: "Dewar's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "밝은 시트러스, 헤더 꿀, 섬세한 배", palate: "바닐라 퍼지, 토피, 구운 오크", finish: "허브의 산뜻함과 꿀 단맛이 남는 마무리",
    description: "최대 30종의 몰트와 그레인 원액을 조합해 과수원 과일, 꿀, 바닐라와 가벼운 연기를 보여주는 듀어스의 클래식 블렌드.",
    priceRange: "₩25,000–35,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "클래식", "하이볼"],
  },
  {
    id: "dewars-21-mizunara", name: "듀어스 21년 미즈나라 캐스크", distillery: "Dewar's",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: 21, abv: 46,
    nose: "바닐라, 꿀, 백단향, 코코넛", palate: "잘 익은 망고, 핵과류, 부드러운 향신료, 구운 시리얼", finish: "코코넛과 미즈나라 향이 실키하게 길게 이어지는 마무리",
    description: "4단계 숙성 공정 뒤 일본산 미즈나라 오크 캐스크로 피니시하고 46도로 병입한 21년 소량 생산 블렌디드 스카치.",
    priceRange: "₩200,000–300,000", difficulty: "상급", tags: ["블렌디드", "Scotch", "미즈나라", "21년"],
  },
  {
    id: "jb-rare", name: "J&B 레어", distillery: "Justerini & Brooks",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "사과, 배, 마른 나무, 시트러스, 보리", palate: "바닐라, 풍부한 과일, 가벼운 몰트", finish: "오크와 향신료가 짧고 매끄럽게 남는 마무리",
    description: "녹칸두·스트라스밀·글렌스페이·오스루스크 등 스페이사이드 몰트를 중심으로 42종의 몰트와 그레인 원액을 조합한 가벼운 블렌드.",
    priceRange: "₩30,000–45,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "라이트", "칵테일"],
  },
  {
    id: "black-bottle-original", name: "블랙 보틀 오리지널", distillery: "Gordon Graham",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "그을린 오크, 꽃향, 달콤하고 매운 연기, 훈제 베이컨", palate: "마른 장작 연기, 바다 소금, 꿀, 바닐라", finish: "모닥불, 향신료, 숯불 토피가 길게 남는 마무리",
    description: "부나하벤 모인 등 아일라 피티드 몰트를 높은 비율로 사용하고 버진 오크의 단맛을 더한 대담하고 스모키한 블렌디드 스카치.",
    priceRange: "₩40,000–60,000", difficulty: "중급", tags: ["블렌디드", "Scotch", "피트", "스모키"],
  },
  {
    id: "naked-malt", name: "네이키드 몰트", distillery: "Naked Malt",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "검은 체리, 잘 구운 빵, 몰트, 복숭아", palate: "건포도, 토피 푸딩, 라즈베리 잼, 커스터드", finish: "코코아, 오크, 은은한 연기가 균형 있게 남는 마무리",
    description: "여러 싱글몰트를 퍼스트필 올로로소 셰리 캐스크에서 추가 숙성해 진한 과일과 초콜릿 풍미를 입힌 블렌디드 몰트.",
    priceRange: "₩45,000–65,000", difficulty: "중급", tags: ["블렌디드몰트", "Scotch", "올로로소셰리", "과일"],
  },
  {
    id: "copper-dog", name: "코퍼 독", distillery: "Copper Dog",
    region: "Speyside", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "토피 사과, 배, 베리, 시트러스, 바닐라 퍼지", palate: "신선한 과일, 몰트, 바닐라, 섬세한 향신료", finish: "과일과 부드러운 오크 스파이스의 깔끔한 여운",
    description: "최소 8종의 스페이사이드 싱글몰트를 오래된 오크 캐스크에서 결합해 과일과 토피의 접근성 좋은 풍미를 만든 블렌디드 몰트.",
    priceRange: "₩50,000–70,000", difficulty: "입문", tags: ["블렌디드몰트", "Scotch", "Speyside", "프루티"],
  },

  // ─── 추가 2차: 싱글몰트 스카치 (지역 다양성·프리미엄 보강) ───
  {
    id: "glenlivet-15", name: "글렌리벳 15년 프렌치 오크 리저브", distillery: "The Glenlivet",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 15, abv: 40,
    nose: "파인애플, 꿀, 바닐라", palate: "정향, 너트, 건포도, 오크 스파이스", finish: "꿀과 시나몬의 중간 길이 피니쉬",
    description: "리무진 프렌치 오크에서 추가 숙성해 부드러운 스파이스와 견과류 풍미를 더한 스페이사이드 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "프렌치오크", "부드러움"],
  },
  {
    id: "highland-park-18", name: "하이랜드 파크 18년 바이킹 프라이드", distillery: "Highland Park",
    region: "Highland (Orkney)", country: "Scotland", category: "싱글몰트", age: 18, abv: 43,
    nose: "성숙한 오크, 꿀, 말린 과일, 은은한 히더 피트 스모크", palate: "캔디드 오렌지, 꿀, 체리, 코코아, 겨울 스파이스", finish: "부드럽고 둥근 긴 피니쉬",
    description: "셰리 숙성과 오크니 특유의 히더 피트가 균형을 이룬 프리미엄 싱글몰트.",
    priceRange: "₩280,000–350,000", difficulty: "상급", tags: ["싱글몰트", "Orkney", "셰리", "프리미엄"],
  },
  {
    id: "lagavulin-8", name: "라가불린 8년", distillery: "Lagavulin",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 8, abv: 48,
    nose: "키퍼 피트, 짭짤한 소금기, 요오드, 잘 익은 배", palate: "묵직한 스모크, 훈제 생선, 사과 껍질, 단 몰트", finish: "길고 건조한 재 같은 피니쉬",
    description: "비교적 어린 숙성에도 라가불린 특유의 강렬한 피트와 짠맛이 살아있는 아일라 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "스모키"],
  },
  {
    id: "laphroaig-quarter-cask", name: "라프로익 쿼터 캐스크", distillery: "Laphroaig",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: null, abv: 48,
    nose: "약품 피트, 요오드, 단 시리얼, 감초", palate: "강한 피트, 바닐라, 보리 단맛, 오크, 후추 스파이스", finish: "피트와 스모크, 오크가 길게 이어지는 피니쉬",
    description: "쿼터 캐스크 추가 숙성으로 오크 접촉을 극대화해 진하고 강렬한 피트를 끌어낸 아일라 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "쿼터캐스크", "강한피트"],
  },
  {
    id: "glendronach-18", name: "글렌드로낙 18년 앨러디스", distillery: "The GlenDronach",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 18, abv: 46,
    nose: "올로로소 셰리, 대추, 건포도, 다크초콜릿, 크리스마스 스파이스", palate: "셰리 단맛, 스튜 과일, 코코아, 오렌지 필, 토스트 호두", finish: "셰리와 다크 프루트, 스파이스가 길게 남는 피니쉬",
    description: "올로로소 셰리 캐스크에서 18년 숙성해 진한 다크 프루트와 초콜릿 풍미가 가득한 프리미엄 하이랜드 싱글몰트.",
    priceRange: "₩190,000–260,000", difficulty: "상급", tags: ["싱글몰트", "Highland", "올로로소셰리", "프리미엄"],
  },
  {
    id: "glenkinchie-12", name: "글렌킨치 12년", distillery: "Glenkinchie",
    region: "Lowland", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "레몬, 풋사과, 꿀, 바닐라, 풀향", palate: "풋과일, 보리 몰트, 코코아, 가벼운 스파이스", finish: "시트러스와 풋사과가 깔끔하게 떨어지는 피니쉬",
    description: "가볍고 산뜻한 풀향과 시트러스가 돋보이는 로우랜드 대표 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "입문", tags: ["싱글몰트", "Lowland", "가벼움", "입문용"],
  },
  {
    id: "caol-ila-12", name: "쿨일라 12년", distillery: "Caol Ila",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "바다 소금, 풀향, 훈제 고기, 시트러스, 오일리한 스모크", palate: "오일리한 타르, 우아한 스모크, 브라인, 가벼운 스파이스", finish: "후추 같은 스파이스와 스모크가 길게 이어지는 피니쉬",
    description: "묵직하지 않으면서 깔끔한 스모크와 바다 향이 균형 잡힌 접근성 좋은 아일라 싱글몰트.",
    priceRange: "₩80,000–110,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "스모키", "해풍"],
  },
  {
    id: "clynelish-14", name: "클라이넬리쉬 14년", distillery: "Clynelish",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 14, abv: 46,
    nose: "꿀, 바닐라, 배, 사과, 특유의 왁시함", palate: "오일리하고 왁시한 질감, 버터스카치, 배, 토피", finish: "스파이스와 꿀, 플로럴함이 길게 남는 피니쉬",
    description: "특유의 왁시한 질감과 꿀, 과일 풍미가 어우러진 하이랜드 코스탈 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Highland", "왁시", "꿀"],
  },

  // ─── 추가 3차: 싱글몰트 스카치 (지역 공백 Campbeltown·Lowland·아일라 다양성·인기) ───
  {
    id: "springbank-10", name: "스프링뱅크 10년", distillery: "Springbank",
    region: "Campbeltown", country: "Scotland", category: "싱글몰트", age: 10, abv: 46,
    nose: "해풍, 오렌지 제스트, 헤더 꿀", palate: "오일리, 후추, 육두구, 과수원 과일", finish: "솔티드 캐러멜, 토피, 은은한 피트",
    description: "버번·셰리 캐스크 숙성으로 캠벨타운 특유의 짭짤한 복합미를 보여주는 대표 싱글몰트.",
    priceRange: "₩100,000–130,000", difficulty: "중급", tags: ["싱글몰트", "캠벨타운", "약한피트", "코스탈"],
  },
  {
    id: "auchentoshan-12", name: "오켄토션 12년", distillery: "Auchentoshan",
    region: "Lowland", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "푸른 사과, 시트러스, 토피", palate: "바닐라, 헤이즐넛, 귤", finish: "생강, 견과류, 가벼운 드라이",
    description: "삼중 증류로 가볍고 부드러운 질감을 지닌 로우랜드 입문용 싱글몰트.",
    priceRange: "₩70,000–90,000", difficulty: "입문", tags: ["싱글몰트", "로우랜드", "삼중증류", "라이트"],
  },
  {
    id: "bunnahabhain-12", name: "부나하벤 12년", distillery: "Bunnahabhain",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: 12, abv: 46.3,
    nose: "건과일, 바닐라, 해초", palate: "셰리, 구운 견과, 설타나", finish: "벨벳 캐러멜, 바다 소금기",
    description: "논칠필터·내추럴 컬러로 병입되는 언피티드 아일라 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "아일라", "언피티드", "셰리"],
  },
  {
    id: "bruichladdich-classic-laddie", name: "브룩라디 더 클래식 라디", distillery: "Bruichladdich",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: null, abv: 50,
    nose: "보리, 레몬, 바닐라, 해염", palate: "후추, 꿀, 몰트 비스킷, 시나몬", finish: "오크 탄닌, 레몬 껍질, 드라이",
    description: "보리 본연의 풍미를 강조한 50도 언피티드 아일라 싱글몰트.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "아일라", "언피티드", "하이프루프"],
  },
  {
    id: "aberfeldy-12", name: "애버펠디 12년", distillery: "Aberfeldy",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "꿀, 헤더, 바닐라, 구운 사과", palate: "버터스카치, 몰트, 시트러스, 시나몬", finish: "부드러운 꿀, 가벼운 스파이스",
    description: "시그니처 꿀맛으로 골든 드램이라 불리는 하이랜드 싱글몰트.",
    priceRange: "₩70,000–90,000", difficulty: "입문", tags: ["싱글몰트", "하이랜드", "꿀", "라이트"],
  },
  {
    id: "glengoyne-12", name: "글렌고인 12년", distillery: "Glengoyne",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "코코넛, 꿀, 레몬 제스트, 오크", palate: "토피 애플, 시나몬, 생강, 오렌지", finish: "은은한 셰리, 부드러운 오크",
    description: "피트를 쓰지 않고 셰리 캐스크로 숙성한 논피트 하이랜드 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["싱글몰트", "하이랜드", "논피트", "셰리"],
  },
  {
    id: "old-pulteney-12", name: "올드 풀트니 12년", distillery: "Old Pulteney",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "레몬, 조개껍질 미네랄, 바닐라, 꿀", palate: "바닐라, 소금기, 시트러스, 생강", finish: "후추, 바다 소금, 오크 드라이",
    description: "북해 해풍을 머금은 코스탈 캐릭터의 해양성 하이랜드 싱글몰트.",
    priceRange: "₩70,000–90,000", difficulty: "중급", tags: ["싱글몰트", "하이랜드", "코스탈", "해양성"],
  },
  {
    id: "cragganmore-12", name: "크라간모어 12년", distillery: "Cragganmore",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "꿀, 말린 허브, 은은한 우드 스모크", palate: "몰트, 견과류, 스톤프루트", finish: "부드러운 스모크와 후추 스파이스가 길게",
    description: "디아지오 클래식 몰트의 일원으로, 복합적이면서도 균형 잡힌 스페이사이드의 정수를 보여주는 싱글몰트.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["싱글몰트", "스페이사이드", "클래식몰트", "복합적"],
  },
  {
    id: "cardhu-12", name: "카듀 12년", distillery: "Cardhu",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 40,
    nose: "사과, 배, 꿀, 바닐라", palate: "토피, 몰트, 과일 단맛", finish: "따뜻한 시리얼과 옅은 스모크",
    description: "조니워커의 핵심 원액으로 쓰이는 부드럽고 접근성 높은 스페이사이드 싱글몰트.",
    priceRange: "₩65,000–85,000", difficulty: "입문", tags: ["싱글몰트", "스페이사이드", "부드러움", "입문"],
  },
  {
    id: "mortlach-16", name: "모틀락 16년 디스틸러스 드램", distillery: "Mortlach",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 16, abv: 43.4,
    nose: "다크 프루트, 호두, 오크 스파이스", palate: "육중한 셰리, 가죽, 살구, 꿀", finish: "묵직한 셰리 단맛이 길고 복합적으로",
    description: "더프타운의 야수로 불리는 묵직한 셰리 캐릭터의 풀바디 싱글몰트.",
    priceRange: "₩130,000–170,000", difficulty: "상급", tags: ["싱글몰트", "스페이사이드", "셰리", "풀바디"],
  },

  // ─── 추가 3차: 세계 위스키 (인도·대만·캐나다·일본 프리미엄) ───
  {
    id: "amrut-fusion", name: "암룻 퓨전", distillery: "Amrut",
    region: "Bangalore", country: "India", category: "기타", age: null, abv: 50,
    nose: "열대과일, 시나몬, 옅은 스모크", palate: "캐러멜, 꿀, 시리얼, 후추 스파이스", finish: "꿀과 스모크가 은은하게 길게",
    description: "인도산 보리와 피트 스코틀랜드 보리를 결합해 100프루프로 병입한 인도 싱글몰트의 대표작.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "인도", "피트", "100프루프"],
  },
  {
    id: "kavalan-solist", name: "카발란 솔리스트 엑스 버번", distillery: "Kavalan",
    region: "Yilan", country: "Taiwan", category: "기타", age: null, abv: 57.8,
    nose: "바닐라, 코코넛, 망고, 시트러스", palate: "꿀, 바닐라, 후추 스파이스, 오크", finish: "열대과일과 후추가 뜨겁고 길게",
    description: "퍼스트필 버번 단일 캐스크를 캐스크스트렝스로 병입한 대만 싱글몰트로 도수는 배럴별로 상이(약 55~58%).",
    priceRange: "₩200,000–260,000", difficulty: "상급", tags: ["싱글몰트", "대만", "싱글캐스크", "캐스크스트렝스"],
  },
  {
    id: "crown-royal-northern-harvest-rye", name: "크라운 로얄 노던 하베스트 라이", distillery: "Crown Royal",
    region: "Manitoba", country: "Canada", category: "기타", age: null, abv: 45,
    nose: "베이킹 스파이스, 시리얼, 옅은 우드 스파이스", palate: "오크, 버터스카치, 스파이스드 바닐라, 후추", finish: "부드럽고 크리미하게",
    description: "라이 90% 매시로 빚어 2016년 올해의 위스키에 오른 캐나다 라이 위스키.",
    priceRange: "₩45,000–60,000", difficulty: "중급", tags: ["캐나디안", "라이", "올해의위스키", "블렌디드"],
  },
  {
    id: "yamazaki-18", name: "야마자키 18년", distillery: "Yamazaki",
    region: "Osaka", country: "Japan", category: "기타", age: 18, abv: 43,
    nose: "올로로소 셰리, 건포도, 말린 과일, 트러플", palate: "꿀, 토피, 다크초콜릿, 흑후추", finish: "마멀레이드와 과일 단맛이 길게",
    description: "셰리 버트 중심으로 숙성한 산토리의 프리미엄 싱글몰트 아이콘.",
    priceRange: "₩1,300,000–1,800,000", difficulty: "상급", tags: ["싱글몰트", "일본", "셰리", "프리미엄"],
  },
  {
    id: "hibiki-21", name: "히비키 21년", distillery: "Suntory",
    region: "Multiple", country: "Japan", category: "기타", age: 21, abv: 43,
    nose: "잘 익은 과일, 꿀 캐러멜, 백단향, 미즈나라 오크", palate: "시나몬, 말린 살구, 다크체리, 토피", finish: "미즈나라 향과 과일 단맛이 길게",
    description: "여러 증류소 원액을 블렌딩한 산토리의 프리미엄 재패니즈 블렌디드 위스키 아이콘.",
    priceRange: "₩2,500,000–3,500,000", difficulty: "상급", tags: ["블렌디드", "일본", "미즈나라", "프리미엄"],
  },

  // ─── 추가 3차: 아메리칸 버번/라이 (휘티드·인기·테네시·라이 프리미엄) ───
  {
    id: "weller-special-reserve", name: "W.L. 웰러 스페셜 리저브", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 45,
    nose: "꿀, 바닐라, 캐러멜", palate: "허니, 부드러운 곡물, 버터스카치", finish: "크리미한 바닐라와 토스티드 오크의 긴 여운",
    description: "라이 대신 밀을 쓴 휘티드 버번으로 부드럽고 달콤해 입문자에게도 좋은 버팔로 트레이스의 인기 보틀.",
    priceRange: "₩70,000–110,000", difficulty: "입문", tags: ["버번", "Kentucky", "휘티드", "부드러움"],
  },
  {
    id: "larceny", name: "라세니", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 46,
    nose: "꿀, 바닐라, 버터", palate: "캐러멜, 토피, 부드러운 곡물", finish: "달콤한 꿀과 오크의 중간 여운",
    description: "헤븐 힐의 대표 휘티드 버번으로 밀 함량이 높아 둥글고 달콤한 풍미가 가성비 좋게 다가오는 보틀.",
    priceRange: "₩60,000–85,000", difficulty: "입문", tags: ["버번", "Kentucky", "휘티드", "가성비"],
  },
  {
    id: "1792-small-batch", name: "1792 스몰 배치", distillery: "Barton 1792",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 46.85,
    nose: "캐러멜, 바닐라, 라이 스파이스", palate: "캐러멜, 시나몬, 오크", finish: "건조하고 스파이시한 긴 여운",
    description: "라이 함량이 높은 하이라이 매시빌로 달콤함 뒤에 또렷한 향신료가 따라오는 바턴 1792의 시그니처 버번.",
    priceRange: "₩60,000–90,000", difficulty: "중급", tags: ["버번", "Kentucky", "하이라이", "스파이시"],
  },
  {
    id: "henry-mckenna-10", name: "헨리 맥케나 10년 보틀드 인 본드", distillery: "Heaven Hill",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 10, abv: 50,
    nose: "오크, 캐러멜, 바닐라", palate: "토피, 라이 스파이스, 건조한 오크", finish: "오크 탄닌과 향신료의 길고 드라이한 여운",
    description: "10년 숙성 싱글배럴 보틀드 인 본드로 100프루프의 묵직한 오크와 향신료가 인상적인 수상 경력의 버번.",
    priceRange: "₩90,000–140,000", difficulty: "중급", tags: ["버번", "Kentucky", "BiB", "싱글배럴"],
  },
  {
    id: "george-dickel-12", name: "조지 디켈 No.12", distillery: "George Dickel",
    region: "Tennessee", country: "USA", category: "테네시", age: null, abv: 45,
    nose: "바닐라, 오크, 메이플", palate: "리치한 오크, 바닐라, 곡물", finish: "메이플 버터와 은은한 스모크의 긴 여운",
    description: "링컨 카운티 프로세스로 메이플 차콜 여과를 거친 테네시 위스키로 부드럽고 균형 잡힌 가성비 보틀.",
    priceRange: "₩50,000–75,000", difficulty: "입문", tags: ["버번", "Tennessee", "테네시", "메이플"],
  },
  {
    id: "whistlepig-10", name: "휘슬피그 10년 라이", distillery: "WhistlePig",
    region: "Vermont", country: "USA", category: "버번/라이", age: 10, abv: 50,
    nose: "꿀, 바닐라, 캐러멜", palate: "베이킹 스파이스, 다크 초콜릿, 민트", finish: "바닐라와 라이 스파이스의 길고 크리미한 여운",
    description: "버몬트 농장에서 10년 숙성·병입하는 100프루프 프리미엄 스트레이트 라이로 라이 특유의 향신료와 크리미함이 돋보이는 보틀.",
    priceRange: "₩130,000–180,000", difficulty: "상급", tags: ["라이", "Vermont", "프리미엄", "10년"],
  },

  // ─── 추가 6차: 테마별 공백 보강 (싱글몰트·블렌디드·아이리쉬·버번·일본) ───
  {
    id: "macallan-double-cask-15", name: "맥캘란 더블 캐스크 15년", distillery: "The Macallan",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 15, abv: 43,
    nose: "말린 과일, 진저브레드, 바닐라, 시트러스", palate: "토피, 오렌지, 스위트 스파이스, 크리미한 오크", finish: "길고 따뜻하며 스파이시한 여운",
    description: "아메리칸·유러피언 오크 셰리 캐스크를 함께 숙성해 12년보다 한층 깊고 진한 단맛을 보여주는 더블 캐스크 상위 라인.",
    priceRange: "₩150,000–200,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "셰리", "더블캐스크"],
  },
  {
    id: "glenfiddich-21", name: "글렌피딕 21년 그란 레세르바", distillery: "Glenfiddich",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 21, abv: 40,
    nose: "다크 초콜릿, 오렌지, 스파이스, 캐러멜라이즈드 슈거", palate: "럼 캐스크의 달콤함, 바나나, 헤이즐넛, 오크", finish: "길고 부드러운 럼 캐스크 여운",
    description: "카리브해 럼 캐스크에서 추가 숙성해 이국적인 단맛과 부드러움을 더한 21년 숙성 프리미엄 스페이사이드.",
    priceRange: "₩280,000–360,000", difficulty: "상급", tags: ["싱글몰트", "Speyside", "럼캐스크", "프리미엄"],
  },
  {
    id: "benromach-10", name: "벤로막 10년", distillery: "Benromach",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 10, abv: 43,
    nose: "바닐라, 몰트, 은은한 스모크, 시트러스", palate: "셰리 단맛, 오크, 가벼운 피트, 과일", finish: "부드럽고 스모키한 중간 길이 여운",
    description: "전통 방식으로 되살린 소규모 증류소의 스타일을 보여주는, 은은한 피트감의 클래식 스페이사이드 싱글몰트.",
    priceRange: "₩70,000–90,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "약한피트", "전통방식"],
  },
  {
    id: "tomatin-12", name: "토마틴 12년", distillery: "Tomatin",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "잘 익은 사과, 바닐라, 꿀", palate: "부드러운 몰트, 오크, 은은한 스파이스", finish: "가볍고 산뜻한 여운",
    description: "버번·셰리 캐스크에서 숙성해 가볍고 접근성 좋은 풍미를 보여주는 하이랜드 입문용 싱글몰트.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["싱글몰트", "Highland", "가벼움", "입문추천"],
  },
  {
    id: "tamdhu-12", name: "탐듀 12년", distillery: "Tamdhu",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "건포도, 오렌지, 셰리, 바닐라", palate: "토피, 다크초콜릿, 스파이스, 견과류", finish: "따뜻하고 묵직한 셰리 여운",
    description: "전량 올로로소 셰리 캐스크에서만 숙성해 진한 과일과 견과 풍미를 보여주는 스페이사이드 싱글몰트.",
    priceRange: "₩75,000–100,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "올로로소셰리", "풀셰리"],
  },
  {
    id: "kilchoman-machir-bay", name: "킬호만 마키어 베이", distillery: "Kilchoman",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: null, abv: 46,
    nose: "레몬, 바닐라, 피트 스모크, 소금기", palate: "달콤한 몰트, 스모크, 시트러스, 후추", finish: "짭짤하고 스모키한 산뜻한 여운",
    description: "아일라에서 보리 재배부터 병입까지 직접 하는 팜 증류소의 대표작으로, 젊지만 신선한 피트 캐릭터가 돋보인다.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글몰트", "Islay", "피트", "팜디스틸러리"],
  },
  {
    id: "deanston-12", name: "딘스턴 12년", distillery: "Deanston",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 12, abv: 46.3,
    nose: "꿀, 바닐라, 시트러스, 갓 구운 빵", palate: "크리미한 몰트, 꿀, 은은한 스파이스", finish: "부드럽고 달콤한 여운",
    description: "논칠필터로 병입해 질감이 크리미하고, 옛 방직 공장을 개조한 증류소로도 유명한 하이랜드 싱글몰트.",
    priceRange: "₩60,000–80,000", difficulty: "입문", tags: ["싱글몰트", "Highland", "논칠필터", "크리미"],
  },
  {
    id: "arran-10", name: "아란 몰트 10년", distillery: "Arran",
    region: "Isle of Arran", country: "Scotland", category: "싱글몰트", age: 10, abv: 46,
    nose: "풋사과, 배, 바닐라, 몰트", palate: "과일, 오크, 가벼운 스파이스", finish: "산뜻하고 깨끗한 여운",
    description: "1995년 재건된 아란 증류소의 대표작으로, 논칠필터의 신선하고 과일향 가득한 아일랜드 싱글몰트.",
    priceRange: "₩65,000–85,000", difficulty: "입문", tags: ["싱글몰트", "Island", "논칠필터", "과일향"],
  },
  {
    id: "something-special", name: "썸싱 스페셜", distillery: "Chivas Brothers",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "꿀, 헤더, 은은한 오크", palate: "부드러운 몰트, 꿀, 가벼운 스파이스", finish: "짧고 부드러운 여운",
    description: "1970~90년대 한국에서 폭발적인 인기를 누렸던 시바스 브라더스의 블렌디드 스카치로, 지금도 올드 스쿨 바에서 만날 수 있다.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "레트로", "한국인기"],
  },
  {
    id: "passport-scotch", name: "패스포트", distillery: "Chivas Brothers",
    region: "Multiple", country: "Scotland", category: "블렌디드", age: null, abv: 40,
    nose: "가벼운 곡물, 꽃향, 시트러스", palate: "라이트한 몰트, 은은한 단맛", finish: "짧고 깔끔한 여운",
    description: "가볍고 부담 없는 스타일로 8090년대 한국 룸살롱·바에서 꾸준히 사랑받았던 블렌디드 스카치.",
    priceRange: "₩30,000–40,000", difficulty: "입문", tags: ["블렌디드", "Scotch", "레트로", "한국인기"],
  },
  {
    id: "powers-johns-lane", name: "파워스 존스 레인 릴리즈", distillery: "Midleton",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: 12, abv: 46,
    nose: "오렌지, 스파이스, 바닐라, 팟스틸 특유의 오일리함", palate: "시나몬, 잘 익은 과일, 오크, 후추", finish: "길고 스파이시한 여운",
    description: "12년 이상 숙성한 싱글 팟 스틸 원액을 캐스크 스트렝스에 가깝게 병입한 파워스의 프리미엄 라인.",
    priceRange: "₩130,000–170,000", difficulty: "상급", tags: ["싱글팟스틸", "아이리쉬", "프리미엄", "캐스크스트렝스급"],
  },
  {
    id: "connemara-peated", name: "코네마라 피티드 싱글몰트", distillery: "Cooley",
    region: "County Louth", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "피트 스모크, 바닐라, 몰트", palate: "스모키, 꿀, 부드러운 곡물", finish: "은은한 스모크가 남는 여운",
    description: "피트를 사용하는 몇 안 되는 아이리쉬 싱글몰트로, 스코틀랜드와는 다른 부드러운 스모키함이 특징이다.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["싱글몰트", "아이리쉬", "피트", "희귀스타일"],
  },
  {
    id: "makers-mark-cask-strength", name: "메이커스 마크 캐스크 스트렝스", distillery: "Maker's Mark",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 55.8,
    nose: "캐러멜, 바닐라, 오크, 진한 곡물향", palate: "묵직한 캐러멜, 시나몬, 뜨거운 오크 스파이스", finish: "길고 강렬한 오크와 스파이스의 여운",
    description: "메이커스 마크를 가수 없이 캐스크 스트렝스 그대로 병입한 버전으로, 도수는 배치마다 약 54~57%로 상이하며 기본 라인보다 훨씬 진하고 강렬한 밀 매시빌 버번이다.",
    priceRange: "₩70,000–95,000", difficulty: "중급", tags: ["버번", "Kentucky", "캐스크스트렝스", "휘티드"],
  },
  {
    id: "1792-bottled-in-bond", name: "1792 보틀드 인 본드", distillery: "Barton 1792",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "캐러멜, 바닐라, 라이 스파이스, 오크", palate: "묵직한 캐러멜, 후추, 건조한 오크", finish: "길고 스파이시한 여운",
    description: "보틀드 인 본드 규정에 따라 최소 4년 숙성·100프루프로 병입한 1792의 진하고 균형 잡힌 라인.",
    priceRange: "₩65,000–90,000", difficulty: "중급", tags: ["버번", "Kentucky", "BiB", "하이라이"],
  },
  {
    id: "eh-taylor-small-batch", name: "E.H. 테일러 스몰 배치", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 50,
    nose: "바닐라, 오크, 민트, 가벼운 과일", palate: "캐러멜, 스파이스, 토스티드 오크", finish: "길고 드라이한 오크 여운",
    description: "버번의 아버지로 불리는 E.H. 테일러 대령의 이름을 딴 보틀드 인 본드 스타일의 프리미엄 버번.",
    priceRange: "₩120,000–160,000", difficulty: "중급", tags: ["버번", "Kentucky", "BiB", "프리미엄"],
  },
  {
    id: "old-grand-dad-114", name: "올드 그랜드대드 114", distillery: "Jim Beam",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 57,
    nose: "오크, 후추, 캐러멜, 민트", palate: "강렬한 라이 스파이스, 캐러멜, 오크", finish: "뜨겁고 긴 스파이시 여운",
    description: "114프루프로 병입한 하이라이 버번으로, 가성비와 강렬한 스파이스감으로 마니아층이 두터운 보틀.",
    priceRange: "₩50,000–70,000", difficulty: "중급", tags: ["버번", "Kentucky", "하이라이", "고도수"],
  },
  {
    id: "mars-iwai-tradition", name: "마스 이와이 트래디션", distillery: "Mars Shinshu",
    region: "Nagano", country: "Japan", category: "기타", age: null, abv: 40,
    nose: "곡물, 바닐라, 가벼운 과일", palate: "부드러운 몰트, 캐러멜, 은은한 스파이스", finish: "짧고 깔끔한 여운",
    description: "혼슈 마스 신슈 증류소의 가볍고 부담 없는 데일리 블렌디드로, 하이볼용으로 특히 인기가 많다.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "Japanese", "하이볼", "가성비"],
  },
  {
    id: "fuji-single-blended", name: "후지 싱글 블렌디드", distillery: "Fuji Gotemba",
    region: "Shizuoka", country: "Japan", category: "기타", age: null, abv: 46,
    nose: "꿀, 바닐라, 열대과일, 오크", palate: "크리미한 몰트, 카라멜, 은은한 스파이스", finish: "부드럽고 따뜻한 여운",
    description: "후지고텐바 증류소 한 곳의 몰트·그레인 원액만으로 블렌딩한 싱글 블렌디드 위스키.",
    priceRange: "₩90,000–120,000", difficulty: "중급", tags: ["싱글블렌디드", "Japanese", "후지산", "프리미엄"],
  },

  // ─── 추가 7차: 카테고리별 공백 보강 (스카치·아이리쉬·버번·일본/캐나다) ───
  {
    id: "glenmorangie-quinta-ruban", name: "글렌모렌지 퀸타 루반", distillery: "Glenmorangie",
    region: "Highland", country: "Scotland", category: "싱글몰트", age: 14, abv: 46,
    nose: "다크 초콜릿, 민트, 레드베리", palate: "초콜릿, 시나몬, 잘 익은 자두", finish: "초콜릿 민트와 오크의 긴 여운",
    description: "버번 캐스크에서 12년 숙성 후 포트 캐스크에서 추가 피니시해 다크 초콜릿과 베리 풍미를 입힌 글렌모렌지의 대표 우드 피니시 라인.",
    priceRange: "₩85,000–110,000", difficulty: "입문", tags: ["싱글몰트", "Highland", "포트캐스크", "우드피니시"],
  },
  {
    id: "ardbeg-corryvreckan", name: "아드벡 코리브레칸", distillery: "Ardbeg",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: null, abv: 57.1,
    nose: "강렬한 피트 스모크, 타르, 블랙페퍼", palate: "다크 초콜릿, 에스프레소, 강한 스모크", finish: "바다소금과 스모크가 아주 길게 이어지는 여운",
    description: "아드벡 10년보다 한층 강렬하고 오일리한 캐스크 스트렝스 라인으로, 스코틀랜드 서쪽 소용돌이 코리브레칸에서 이름을 땄다.",
    priceRange: "₩140,000–180,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "캐스크스트렝스"],
  },
  {
    id: "bruichladdich-octomore", name: "브룩라디 옥토모어", distillery: "Bruichladdich",
    region: "Islay", country: "Scotland", category: "싱글몰트", age: null, abv: 59,
    nose: "압도적인 피트 스모크, 요오드, 바닐라", palate: "강한 스모크와 단맛의 대비, 타르, 시트러스", finish: "재와 스모크가 매우 길게 남는 여운",
    description: "세계에서 가장 높은 피트 수치(ppm)로 유명한 브룩라디의 익스트림 피트 라인으로, 에디션마다 피트 수치와 도수가 달라진다.",
    priceRange: "₩180,000–260,000", difficulty: "상급", tags: ["싱글몰트", "Islay", "피트", "하이피트"],
  },
  {
    id: "glenallachie-12", name: "글렌알라키 12년", distillery: "GlenAllachie",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 46,
    nose: "올로로소·PX 셰리, 다크 초콜릿, 오렌지필", palate: "꿀, 모카, 건과일, 스파이스", finish: "꿀과 모카가 길게 남는 여운",
    description: "전 글렌드로낙 마스터 블렌더 빌리 워커가 이끄는 증류소의 대표작으로, 진한 셰리 캐스크 풍미로 최근 몇 년간 커뮤니티에서 급부상한 가성비 셰리 싱글몰트.",
    priceRange: "₩105,000–140,000", difficulty: "중급", tags: ["싱글몰트", "Speyside", "셰리", "가성비"],
  },
  {
    id: "haig-club", name: "헤이그 클럽", distillery: "Cameronbridge",
    region: "Lowland", country: "Scotland", category: "논몰트", age: null, abv: 40,
    nose: "꿀, 바닐라, 가벼운 시트러스", palate: "토피, 부드러운 곡물, 은은한 스파이스", finish: "짧고 부드러운 곡물 여운",
    description: "카메론브리지 증류소에서 만든 싱글 그레인 위스키로, 부드럽고 가벼운 스타일 덕에 하이볼로 특히 즐기기 좋다.",
    priceRange: "₩80,000–110,000", difficulty: "입문", tags: ["싱글그레인", "Lowland", "하이볼", "부드러움"],
  },
  {
    id: "glen-grant-12", name: "글렌 그랜트 12년", distillery: "Glen Grant",
    region: "Speyside", country: "Scotland", category: "싱글몰트", age: 12, abv: 43,
    nose: "풋사과, 배, 은은한 꽃향", palate: "가벼운 몰트, 바닐라, 산뜻한 과일", finish: "깔끔하고 산뜻한 여운",
    description: "짐 머레이 위스키 바이블에서 높은 점수를 여러 차례 받은 스테디셀러로, 가볍고 과일향이 살아있는 입문용 스페이사이드.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["싱글몰트", "Speyside", "과일향", "입문추천"],
  },
  {
    id: "kilbeggan", name: "킬베간", distillery: "Kilbeggan Distillery",
    region: "County Westmeath", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "캐러멜, 바닐라, 복숭아", palate: "아몬드 누가, 부드러운 곡물, 가벼운 단맛", finish: "부드럽고 짧은 여운",
    description: "세계에서 가장 오래된 증류 면허를 보유한 킬베간 증류소의 이름을 딴 가볍고 부담 없는 데일리 블렌드.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "데일리", "가성비"],
  },
  {
    id: "proper-no-twelve", name: "프로퍼 트웰브", distillery: "West Cork Distillers",
    region: "County Cork", country: "Ireland", category: "아이리쉬", age: null, abv: 40,
    nose: "꿀, 바닐라, 은은한 꽃향", palate: "가벼운 스파이스, 부드러운 곡물", finish: "깔끔하고 짧은 여운",
    description: "UFC 파이터 코너 맥그리거가 론칭해 국내 바 문화에서도 인지도가 높은 아이리쉬 블렌드.",
    priceRange: "₩35,000–50,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "데일리", "대중적"],
  },
  {
    id: "roe-and-co", name: "로 앤 코", distillery: "Roe & Co Distillery",
    region: "Dublin", country: "Ireland", category: "아이리쉬", age: null, abv: 45,
    nose: "토피, 바닐라, 부드러운 스파이스", palate: "꿀, 크리미한 몰트, 은은한 오크", finish: "짧고 달콤한 여운",
    description: "디아지오가 더블린에 세운 현대적 크래프트 증류소로, 조니워커식 블렌딩 노하우를 아이리쉬에 적용한 브랜드.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["블렌디드", "아이리쉬", "더블린", "모던"],
  },
  {
    id: "pappy-van-winkle-15", name: "패피 반 윙클 패밀리 리저브 15년", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 15, abv: 53.5,
    nose: "캐러멜, 말린 과일, 가죽", palate: "베이킹 스파이스, 오크, 깊은 단맛", finish: "매우 길고 복합적인 오크 여운",
    description: "전 세계 위스키 커뮤니티에서 가장 자주 회자되는 희귀 버번으로, 정가로는 사실상 구하기 힘들어 프리미엄이 크게 붙는다.",
    priceRange: "₩1,500,000–2,500,000", difficulty: "상급", tags: ["버번", "Kentucky", "희귀", "프리미엄"],
  },
  {
    id: "weller-12", name: "W.L. 웰러 12년", distillery: "Buffalo Trace",
    region: "Kentucky", country: "USA", category: "버번/라이", age: 12, abv: 45,
    nose: "아몬드, 바닐라, 캐러멜", palate: "깊은 단맛, 오크, 복합적인 스파이스", finish: "길고 매끄러운 여운",
    description: "'가난한 자의 패피'로 불리며 웰러 스페셜 리저브보다 한 단계 위인 휘티드 버번의 상위 라인으로 커뮤니티에서 특히 자주 언급된다.",
    priceRange: "₩180,000–250,000", difficulty: "중급", tags: ["버번", "Kentucky", "휘티드", "희귀"],
  },
  {
    id: "four-roses-yellow-label", name: "포 로지스 옐로우 라벨", distillery: "Four Roses",
    region: "Kentucky", country: "USA", category: "버번/라이", age: null, abv: 40,
    nose: "꽃향, 과일향, 부드러운 캐러멜", palate: "가벼운 스파이스, 크리미한 바닐라", finish: "짧고 부드러운 여운",
    description: "포 로지스의 가장 기본이 되는 입문용 버번으로, 마트·편의점에서도 쉽게 구할 수 있는 가벼운 스타일.",
    priceRange: "₩40,000–55,000", difficulty: "입문", tags: ["버번", "Kentucky", "입문추천", "가성비"],
  },
  {
    id: "nikka-coffey-grain", name: "닛카 커피 그레인", distillery: "Nikka",
    region: "Hyogo (Nishinomiya)", country: "Japan", category: "기타", age: null, abv: 45,
    nose: "바닐라, 캐러멜, 자몽", palate: "멜론, 크리미한 곡물, 은은한 오크", finish: "부드럽고 크리미한 여운",
    description: "커피식 연속증류기로 만든 독특한 그레인 위스키로, 버번 같은 단맛과 화사한 과실향이 공존하는 닛카의 대표 그레인 라인.",
    priceRange: "₩120,000–160,000", difficulty: "중급", tags: ["그레인위스키", "Japanese", "커피스틸", "화사함"],
  },
  {
    id: "canadian-club", name: "캐네디언 클럽", distillery: "Hiram Walker & Sons",
    region: "Windsor, Ontario", country: "Canada", category: "기타", age: null, abv: 40,
    nose: "가벼운 라이 스파이스, 바닐라", palate: "캐러멜, 부드러운 곡물", finish: "짧고 부드러운 여운",
    description: "1980~2000년대 한국에서 크라운 로얄 못지않게 유통되던 역사적 스테디셀러 캐나디안 위스키.",
    priceRange: "₩30,000–45,000", difficulty: "입문", tags: ["캐나디안", "블렌디드", "레트로", "한국인기"],
  },
  {
    id: "ichiros-malt-grain-white", name: "이치로즈 몰트 앤 그레인 화이트 라벨", distillery: "Venture Whisky (Chichibu)",
    region: "Saitama", country: "Japan", category: "기타", age: null, abv: 46,
    nose: "꿀, 트로피컬 과일, 오크 스파이스", palate: "은은한 스모크, 몰트, 크리미한 단맛", finish: "부드럽고 은은한 스모키 여운",
    description: "전 세계 각지의 몰트·그레인 원액을 블렌딩하는 독특한 월드 블렌디드 컨셉으로, 최근 수년간 재패니즈 위스키 커뮤니티에서 가장 화제가 된 브랜드.",
    priceRange: "₩150,000–220,000", difficulty: "상급", tags: ["블렌디드", "Japanese", "월드블렌디드", "희소성"],
  },

  // ─── 추가 8차: 논몰트(그레인) 스카치·테네시 위스키 카테고리 보강 ───
  {
    id: "compass-box-hedonism", name: "컴파스 박스 헤도니즘", distillery: "Compass Box",
    region: "Scotland (Blended)", country: "Scotland", category: "논몰트", age: null, abv: 46,
    nose: "카페라떼, 버터스카치, 오렌지크림", palate: "누가, 구운 헤이즐넛, 우디한 단맛", finish: "밀크초콜릿이 남는 여운",
    description: "몰트가 아닌 그레인 원액만을 블렌딩한 독특한 컨셉의 논칠필터 위스키로, 크리미하고 달콤한 그레인 특유의 개성을 보여준다.",
    priceRange: "₩190,000–230,000", difficulty: "중급", tags: ["그레인위스키", "Scotch", "블렌디드그레인", "논칠필터"],
  },
  {
    id: "loch-lomond-single-grain", name: "로크로몬드 싱글 그레인", distillery: "Loch Lomond Distillery",
    region: "Highland (Loch Lomond)", country: "Scotland", category: "논몰트", age: null, abv: 46,
    nose: "바닐라, 청사과, 배, 코코넛", palate: "초콜릿, 진저, 크리미한 바닐라", finish: "넛맥과 클로브, 오크가 남는 여운",
    description: "코페이식 연속증류기로 만든 접근성 좋은 싱글 그레인 위스키로, 부드럽고 달콤해 그레인 위스키 입문용으로 알맞다.",
    priceRange: "₩55,000–75,000", difficulty: "입문", tags: ["싱글그레인", "Highland", "부드러움", "입문추천"],
  },
  {
    id: "jack-daniels-single-barrel-select", name: "잭 다니엘스 싱글배럴 셀렉트", distillery: "Jack Daniel's",
    region: "Tennessee", country: "USA", category: "테네시", age: null, abv: 47,
    nose: "캐러멜, 스파이스, 밝은 과일향", palate: "오크, 라이 스파이스, 단맛", finish: "중간 길이의 스파이시한 여운",
    description: "릭하우스 상단의 배럴 중에서만 선별해 병입한 잭 다니엘스의 싱글 배럴 라인으로, 기본 올드 No.7보다 진하고 개성 있는 오크 풍미를 보여준다.",
    priceRange: "₩75,000–100,000", difficulty: "중급", tags: ["테네시", "Tennessee", "싱글배럴", "차콜멜로잉"],
  },
  {
    id: "jack-daniels-bonded", name: "잭 다니엘스 본디드", distillery: "Jack Daniel's",
    region: "Tennessee", country: "USA", category: "테네시", age: null, abv: 50,
    nose: "콘플레이크, 시나몬, 진저, 민트", palate: "캐러멜 케이크, 구운 옥수수, 베이킹 스파이스", finish: "스파이시하고 달콤한 중간 길이 여운",
    description: "보틀드 인 본드 규정(4년 이상 숙성·100프루프)에 맞춰 병입한 잭 다니엘스의 상위 라인으로, 기본 라인보다 묵직하고 스파이시하다.",
    priceRange: "₩55,000–75,000", difficulty: "중급", tags: ["테네시", "Tennessee", "BiB", "차콜멜로잉"],
  },
  {
    id: "george-dickel-bottled-in-bond", name: "조지 디켈 바틀 인 본드", distillery: "George Dickel",
    region: "Tennessee", country: "USA", category: "테네시", age: null, abv: 50,
    nose: "버터스카치, 캐러멜, 꿀, 구운 땅콩", palate: "탄 캐러멜, 바닐라, 토스티드 오크, 베이킹 스파이스", finish: "파운드케이크 같은 중~장 여운",
    description: "실제로는 11~13년 원액을 사용하지만 라벨은 무연수로 표기하는 조지 디켈의 보틀드 인 본드 라인으로, 진하고 묵직한 오크 풍미가 특징이다.",
    priceRange: "₩90,000–110,000", difficulty: "중급", tags: ["테네시", "Tennessee", "BiB", "메이플"],
  },
  {
    id: "uncle-nearest-1856", name: "언클 니어리스트 1856", distillery: "Uncle Nearest Distillery",
    region: "Shelbyville, Tennessee", country: "USA", category: "테네시", age: null, abv: 50,
    nose: "메이플, 바닐라, 체리, 블랙페퍼", palate: "캐러멜, 마지팬, 초콜릿 코팅 체리, 크렘브륄레", finish: "길고 진하며 달콤한 여운",
    description: "잭 다니엘에게 증류 기술을 전수한 것으로 알려진 네이선 '니어리스트' 그린을 기리는 브랜드로, 8~14년 원액을 블렌딩한 진하고 풍부한 테네시 위스키.",
    priceRange: "₩90,000–130,000", difficulty: "중급", tags: ["테네시", "Tennessee", "역사", "프리미엄"],
  },
];

export const CATEGORY_TO_TYPE: Record<string, string> = {
  "싱글몰트": "Scotch",
  "블렌디드": "Scotch",
  "논몰트": "Scotch",
  "아이리쉬": "Irish",
  "버번/라이": "Bourbon/Rye",
  "테네시": "Bourbon/Rye",
  "기타": "Etc",
};
